#!/usr/bin/env bash

# to narrow projs.conf to just one project and its dependencies:
#   % ./narrow scalacheck
# or several
#   % ./narrow scalacheck scalatest specs2

# dependencies.txt is the source of truth for what dependencies to use

set -e

# as per https://github.com/coursier/coursier/issues/2058
cs launch \
  scala3-compiler:3+ \
  -M dotty.tools.MainGenericRunner \
  --extra-jars $(cs fetch --intransitive com.github.pathikrit:better-files_2.13:3.9.1) \
  -- scripts/Narrow.scala $*
