#!/usr/bin/env bash

set -e

# otherwise these directories just keep growing.
# see scala/scala-jenkins-infra#115
rm -rf target-*/project-builds
rm -rf target-*/extraction

# the `projects` jenkins job param can be used to limit the projects to build
./run.sh $projects
