#!/usr/bin/env bash

DBUILDVERSION=0.9.4

# prevent crosstalk between jdk6 and jdk8 community builds
# TODO: obv, it would be more elegant to key off `jvmSelect`
CACHEDIR=~/.dbuild/cache-$DBUILDVERSION-jdk8

# otherwise these directories just keep growing.
# see scala/scala-jenkins-infra#115
rm -rf target-$DBUILDVERSION/project-builds
rm -rf target-$DBUILDVERSION/extraction

scripts/dbuild-runner.sh "community.dbuild" "$DBUILDVERSION" \
  "-Ddbuild.cache.dir=$CACHEDIR" \
  "${@}"
