// https://github.com/lightbend/genjavadoc.git#main

vars.proj.genjavadoc: ${vars.base} {
  name: "genjavadoc"
  uri: "https://github.com/lightbend/genjavadoc.git#d26edf3a8b9c7ff9f96c382e54e308ccf80645f6"

}
