// https://github.com/lightbend/genjavadoc.git#main

vars.proj.genjavadoc: ${vars.base} {
  name: "genjavadoc"
  uri: "https://github.com/lightbend/genjavadoc.git#b0dccbc9df9632aa3e36bf67b77e140360b2e459"

}
