// https://github.com/SethTisue/genjavadoc.git#scala-2.13.18  # was lightbend, mainb

// unfork once this is merged:
// https://github.com/lightbend/genjavadoc/pull/398

vars.proj.genjavadoc: ${vars.base} {
  name: "genjavadoc"
  uri: "https://github.com/SethTisue/genjavadoc.git#bb48ad9198db84873e1598b9e5f957395b4f1f85"

}
