// https://github.com/scalameta/scalafmt.git#main

vars.proj.scalafmt: ${vars.base} {
  name: "scalafmt"
  uri: "https://github.com/scalameta/scalafmt.git#e78a86edaa0a31f6bf1e3c42411107ac479b3970"

  extra.projects: ["coreJVM", "cli", "tests", "dynamic"]
  extra.commands: ${vars.default-commands} [
    // context: https://github.com/scalameta/scalafmt/pull/4497
    """set ThisBuild / dependencyOverrides -= "org.jline" % "jline" % "3.23.0""""
    // not investigated? I don't remember
    """set tests.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "CliTest.scala" || "GitOpsTest.scala""""
    """set dynamic.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "DynamicSuite.scala""""
  ]
}
