// https://github.com/scalameta/scalameta.git#v4.14.1  # was main

// we often use a tag here rather than track a branch, in the
// interest of stability.  whatever tag scalafmt and/or scalafix and/or metals expect

// as of October 2025, 4.14.1 is the version both scalafix and scalafmt expect

vars.proj.scalameta: ${vars.base} {
  name: "scalameta"
  uri: "https://github.com/scalameta/scalameta.git#d5fe382407dbe22e6b87b17df852a22ffd3c01c3"

  extra.projects: ["semanticdbScalacPlugin", "testkitJVM"]
  extra.commands: ${vars.default-commands} [
    // use right version-specific source directories regardless of our weird dbuild Scala version numbers
    """set common.jvm / Compile / unmanagedSourceDirectories += baseDirectory.value / "scalameta" / "common" / "shared" / "src" / "main" / "scala-2.13""""
    """set semanticdbScalacCore / Compile / unmanagedSourceDirectories += baseDirectory.value / "semanticdb" / "scalac" / "library" / "src" / "main" / "scala-2.13""""
  ]
}
