// https://github.com/scalacenter/scalafix.git#main

vars.proj.scalafix: ${vars.base} {
  name: "scalafix"
  uri: "https://github.com/scalacenter/scalafix.git#a18fe12999ebdabb16f06c65e24f5426afbb6637"

  extra.options: ["-Dscala213.nightly="${vars.scala-version}]
  extra.projects: ["*2_13*"]
  extra.exclude: ["docs2_13", "*3_5_*"]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -release 8"
    // not investigated
    """set unit.allProjects.map(_._1).find(_.id.startsWith("unit2_13_")).get / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "CliGitDiffSuite.scala""""
    // not investigated; it's not finding a dbuild-built scalafix-cli artifact when running the tests
    """set integration.allProjects.map(_._1).find(_.id.startsWith("integration2_13_")).get / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"""
  ]
}
