// https://github.com/scalameta/scalafmt.git#main

// in scalafmt repo, expected scalameta version is `scalametaV`
// in `project/Dependencies.scala`

vars.proj.scalafmt: ${vars.base} {
  name: "scalafmt"
  uri: "https://github.com/scalameta/scalafmt.git#ae5d7a3b19b12915e8710f88e970c6d36f9ef695"

  extra.projects: ["coreJVM", "cli", "tests", "dynamic"]
  extra.commands: ${vars.default-commands} [
    // CliTest uses mdoc which requires Java 11+, and dbuild hangs.
    // we lack a slicker way to tell dbuild not to even try to build the project
    // on Java 8, so:
    """eval require(scala.util.Properties.isJavaAtLeast("11"))"""
    // context: https://github.com/scalameta/scalafmt/pull/4497
    """set ThisBuild / dependencyOverrides -= "org.jline" % "jline" % "3.23.0""""
    // not investigated? I don't remember
    """set tests.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "CliTest.scala""""
    """set sysops.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "GitOpsTest.scala""""
    """set dynamic.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "DynamicSuite.scala""""
  ]
}
