// https://github.com/scalameta/scalameta.git#v4.14.7  # was main

// we often use a tag here rather than track a branch, in the
// interest of stability.  whatever tag scalafmt and/or scalafix and/or metals expect

// as of 9 February 2026, 4.14.7 is the version scalafmt expects,
// and scalafix is apparently okay with it

vars.proj.scalameta: ${vars.base} {
  name: "scalameta"
  uri: "https://github.com/scalameta/scalameta.git#a4cbeed906615caee8c5ac3553cc1ab8e1fbac95"

  extra.projects: ["semanticdbScalacPlugin", "testkitJVM"]
  extra.commands: ${vars.default-commands} [
    // use right version-specific source directories regardless of our weird dbuild Scala version numbers
    """set common.jvm / Compile / unmanagedSourceDirectories += baseDirectory.value / "scalameta" / "common" / "shared" / "src" / "main" / "scala-2.13""""
    """set semanticdbScalacCore / Compile / unmanagedSourceDirectories += baseDirectory.value / "semanticdb" / "scalac" / "library" / "src" / "main" / "scala-2.13""""
  ]
}
