// https://github.com/scalameta/scalameta.git#v4.13.7  # was main

// we often use a tag here rather than track a branch, in the
// interest of stability.  whatever tag scalafmt and/or scalafix and/or metals expect

// as of August 2025, 4.13.7 is the version scalafix expects

vars.proj.scalameta: ${vars.base} {
  name: "scalameta"
  uri: "https://github.com/scalameta/scalameta.git#0e19b9489ea254a44bacf930b6119d05aa5dadb6"

  extra.projects: ["semanticdbScalacPlugin", "testkitJVM"]
  extra.commands: ${vars.default-commands} [
    // use right version-specific source directories regardless of our weird dbuild Scala version numbers
    """set common.jvm / Compile / unmanagedSourceDirectories += baseDirectory.value / "scalameta" / "common" / "shared" / "src" / "main" / "scala-2.13""""
    """set semanticdbScalacCore / Compile / unmanagedSourceDirectories += baseDirectory.value / "semanticdb" / "scalac" / "library" / "src" / "main" / "scala-2.13""""
  ]
}
