import better.files._

@main def narrow(args: String*) =
  val projs =
    if (args.isEmpty)
      File("proj")
        .list(_.extension == Some(".conf"))
        .map(_.nameWithoutExtension)
    else
      args
  val out = File("projs.conf")
  out.clear()
  out.appendLine("// automatically generated by `narrow` script")
  out.appendLine()
  for (proj <- projs.toSeq.sorted)
    out.append(
      s"""|build += {
          |  space: scala.$proj
          |  check-missing: [false, false]
          |  cross-version: [disabled, standard]
          |  extraction-version: $${vars.scala-version}
          |  sbt-version: $${vars.sbt-version}
          |  sbt-java-options: $${vars.sbt-java-options}
          |  projects: [$${vars.proj.$proj}]
          |}
          |""".stripMargin)
