// https://github.com/geirolz/advxml.git#main

vars.proj.advxml: ${vars.base} {
  name: "advxml"
  uri: "https://github.com/geirolz/advxml.git#01ca690fb91ad8bd9e1d877276adb4d11475343b"

  extra.settings: ${vars.base.extra.settings} [
    // resolve version conflict (from sbt-scoverage, probably?)
    // one-deeper nesting level makes it apply to build definition
    ["""ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always"""]
  ]
}
