// https://github.com/geirolz/advxml.git#main

vars.proj.advxml: ${vars.base} {
  name: "advxml"
  uri: "https://github.com/geirolz/advxml.git#2589134bba44d30b7a31fcf3e94493645789aac7"

  extra.settings: ${vars.base.extra.settings} [
    // resolve version conflict (from sbt-scoverage, probably?)
    // one-deeper nesting level makes it apply to build definition
    ["""ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always"""]
  ]
}
