// https://github.com/geirolz/advxml.git#main

vars.proj.advxml: ${vars.base} {
  name: "advxml"
  uri: "https://github.com/geirolz/advxml.git#01ca690fb91ad8bd9e1d877276adb4d11475343b"

  extra.commands: ${vars.default-commands} [
    "appendScalacOptions -Xsource-features:eta-expand-always"
  ]
}
