// https://github.com/akka/akka-http-webgoat.git#main

vars.proj.akka-http-webgoat: ${vars.base} {
  name: "akka-http-webgoat"
  uri: "https://github.com/akka/akka-http-webgoat.git#1487f341af095df98bc3e432aed579e37eb588b6"

}
