// https://github.com/akka/akka-http-webgoat.git#main

vars.proj.akka-http-webgoat: ${vars.base} {
  name: "akka-http-webgoat"
  uri: "https://github.com/akka/akka-http-webgoat.git#a8c275d9e5907dc7331a2f2f8517cd98d528d7ad"

}
