// https://github.com/akka/akka-http-webgoat.git#main

vars.proj.akka-http-webgoat: ${vars.base} {
  name: "akka-http-webgoat"
  uri: "https://github.com/akka/akka-http-webgoat.git#a8db80099c9872b37d84103e8fe638dbd8793822"

}
