// https://github.com/scalacommunitybuild/akka-http.git#community-build-2.13 # was akka, v10.2.10

// frozen before Akka license change

vars.proj.akka-http: ${vars.base} {
  name: "akka-http"
  uri: "https://github.com/scalacommunitybuild/akka-http.git#2c163141f344cc2dcdb9938dc4263e3a23fce44b"

  extra.exclude: [
    "docs", "akka-http-bench-jmh"
    // our scalafix version is too new
    "akka-http-scalafix-tests"
  ]
  extra.options: [
    "-Xmx4g"
    // otherwise it defaults to Akka 2.5 and there are problems on JDK 17
    "-Dakka.http.build.akka.version=2.6.18"
    // not sure if still necessary, but it's fine
    "-Dakka.genjavadoc.enabled=false", "-Dakka.scaladoc.diagrams=false"
    // this is for the tests that run unforked...
    "-Dakka.fail-mixed-versions=false"
  ]
  extra.commands: ${vars.default-commands} [
    // ...and this is for the tests that run forked
    """set ThisBuild / javaOptions += "-Dakka.fail-mixed-versions=false""""
  ]
}
