// https://github.com/scalacommunitybuild/Ammonite.git#community-build-2.13  # was com-lihaoyi, main

// forked to add sbt build (instead of mill); fork refreshed February 2025

vars.proj.ammonite: ${vars.base} {
  name: "ammonite"
  uri: "https://github.com/scalacommunitybuild/Ammonite.git#800b3580cebc778552ab1185690efbd3484dbacc"

  // it would be nice to actually run the tests and not just compile them...
  extra.test-tasks: ["compile"]
}
