// https://github.com/scalacommunitybuild/Ammonite.git#community-build-2.13  # was com-lihaoyi, main

// forked to add sbt build (instead of mill); fork refreshed February 2025

vars.proj.ammonite: ${vars.base} {
  name: "ammonite"
  uri: "https://github.com/scalacommunitybuild/Ammonite.git#9d44af84c50f823ecb720443fc703ac8839b4062"

  // it would be nice to actually run the tests and not just compile them...
  extra.test-tasks: ["compile"]
}
