// https://github.com/polyvariant/better-tostring.git#main

vars.proj.better-tostring: ${vars.base} {
  name: "better-tostring"
  uri: "https://github.com/polyvariant/better-tostring.git#bc47b40e42a2f45a79a41583ea509b09d5b2b692"

}
