// https://github.com/polyvariant/better-tostring.git#main

vars.proj.better-tostring: ${vars.base} {
  name: "better-tostring"
  uri: "https://github.com/polyvariant/better-tostring.git#3a6d4a949d37612b83d5b9a3d763fe526ebb5bff"

}
