// https://github.com/polyvariant/better-tostring.git#main

vars.proj.better-tostring: ${vars.base} {
  name: "better-tostring"
  uri: "https://github.com/polyvariant/better-tostring.git#0e3ca4616c38a207e9b8b2b061cc4f7d12a76d82"

}
