// https://github.com/suzaku-io/boopickle.git#master

vars.proj.boopickle: ${vars.base} {
  name: "boopickle"
  uri: "https://github.com/suzaku-io/boopickle.git#defac66191a563138dad991c72a1d664091985ac"

  extra.projects: ["boopickleJVM", "shapelessJVM"]  // no Scala.js, no "perftests"
}
