// https://github.com/playframework/cachecontrol.git#main

vars.proj.cachecontrol: ${vars.base} {
  name: "cachecontrol"
  uri: "https://github.com/playframework/cachecontrol.git#f87fa40844ac158426df6c0eb809deb54d83e3be"

  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
