// https://github.com/playframework/cachecontrol.git#main

vars.proj.cachecontrol: ${vars.base} {
  name: "cachecontrol"
  uri: "https://github.com/playframework/cachecontrol.git#f24f5c54cfbe1000399115492b231174f905a2d4"

  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
