// https://github.com/playframework/cachecontrol.git#485f49c8ed48814b2b796760071a254ed16c010a  # was main

// frozen (June 2025) at an April 2025 commit before sbt-java-formatter
// was upgraded to a version that doesn't run on Java 8

vars.proj.cachecontrol: ${vars.base} {
  name: "cachecontrol"
  uri: "https://github.com/playframework/cachecontrol.git#485f49c8ed48814b2b796760071a254ed16c010a"

  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
