// https://github.com/ChristopherDavenport/cats-time.git#main

vars.proj.cats-time: ${vars.base} {
  name: "cats-time"
  uri: "https://github.com/ChristopherDavenport/cats-time.git#31c4f4c16faf81249c921d86cfa744429c43c697"

  extra.exclude: ["*JS", "*Native", "docs"]
}
