// https://github.com/typelevel/cats-mtl.git#main

vars.proj.cats-mtl: ${vars.base} {
  name: "cats-mtl"
  uri: "https://github.com/typelevel/cats-mtl.git#fd44515e2ef489631e5437ca162e72a20c0874da"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // use right version-specific source directories regardless of our weird dbuild Scala version numbers
    """set core.jvm / Compile / unmanagedSourceDirectories += baseDirectory.value / "core" / "src" / "main" / "scala-2.13""""
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
