// https://github.com/cb372/cats-retry.git#series/3.x

// main/4.x is Scala 3 only

vars.proj.cats-retry: ${vars.base} {
  name: "cats-retry"
  uri: "https://github.com/cb372/cats-retry.git#c0c9356c2eed3037d6ca4e0d88b6c32ae6a3cdd2"

  extra.projects: ["coreJVM"]
}
