// https://github.com/typelevel/cats-effect-cps.git#main

vars.proj.cats-effect-cps: ${vars.base} {
  name: "cats-effect-cps"
  uri: "https://github.com/typelevel/cats-effect-cps.git#2c3501aa6c2ab92d5e10bd0560eb61141d9939d3"

  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.11""""
  ]
  extra.exclude: ["*JS", "*Native"]
}
