// https://github.com/cb372/cats-retry.git#main

vars.proj.cats-retry: ${vars.base} {
  name: "cats-retry"
  uri: "https://github.com/cb372/cats-retry.git#3ee165e2158819f00e6382a3b802fbb6c8b07020"

  extra.projects: ["coreJVM"]
}
