// https://github.com/ChristopherDavenport/cats-time.git#main

vars.proj.cats-time: ${vars.base} {
  name: "cats-time"
  uri: "https://github.com/ChristopherDavenport/cats-time.git#99c399665cfabe3abc2f456cd378eeeb82b06c55"

  extra.exclude: ["*JS", "*Native", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
