// https://github.com/typelevel/cats-effect-cps.git#main

vars.proj.cats-effect-cps: ${vars.base} {
  name: "cats-effect-cps"
  uri: "https://github.com/typelevel/cats-effect-cps.git#52253df2dd10ed6184c7a1013a5a036b2d11e0d4"

  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.11""""
  ]
  extra.exclude: ["*JS", "*Native"]
}
