// https://github.com/typelevel/cats-time.git#main

vars.proj.cats-time: ${vars.base} {
  name: "cats-time"
  uri: "https://github.com/typelevel/cats-time.git#95bc969930ccc403eea37b67fe18f9780e79ae9a"

  extra.exclude: ["*JS", "*Native", "docs"]
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
