// https://github.com/typelevel/cats-effect-direct.git#main

vars.proj.cats-effect-direct: ${vars.base} {
  name: "cats-effect-direct"
  uri: "https://github.com/typelevel/cats-effect-direct.git#52253df2dd10ed6184c7a1013a5a036b2d11e0d4"

  extra.options: [
    "--add-exports", "java.base/jdk.internal.vm=ALL-UNNAMED"
  ]
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.11""""
  ]
  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
     """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
