// https://github.com/typelevel/cats-effect.git#series/3.x

vars.proj.cats-effect: ${vars.base} {
  name: "cats-effect"
  uri: "https://github.com/typelevel/cats-effect.git#8c15bb9a1e09028345f02d33da445464a65e08d3"

  extra.exclude: [
    "*JS", "*Native", "benchmarks", "docs"
  ]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
