// https://github.com/cb372/cats-retry.git#main

vars.proj.cats-retry: ${vars.base} {
  name: "cats-retry"
  uri: "https://github.com/cb372/cats-retry.git#c365270bb55e0e51ec1ad4c8ae76f715d39c855f"

  extra.projects: ["coreJVM"]
}
