// https://github.com/scalalandio/chimney.git#master

vars.proj.chimney: ${vars.base} {
  name: "chimney"
  uri: "https://github.com/scalalandio/chimney.git#3416316106d920847cb2eb511d1253b2a4b48ef1"

  extra.exclude: ["*3", "*2_12", "*JS", "*Native", "benchmarks", "chimneySandwichTests"]
  extra.commands: ${vars.default-commands} [
    "appendScalacOptions -Xsource-features:eta-expand-always"
  ]
}
