// https://github.com/scalalandio/chimney.git#master

vars.proj.chimney: ${vars.base} {
  name: "chimney"
  uri: "https://github.com/scalalandio/chimney.git#f92dd4322da7abd257a0082d52b54b119df91ef5"

  extra.exclude: ["*3", "*2_12", "*JS", "*Native", "benchmarks", "chimneySandwichTests"]
  extra.commands: ${vars.default-commands} [
    "appendScalacOptions -Xsource-features:eta-expand-always"
  ]
}
