// https://github.com/scalalandio/chimney.git#master

vars.proj.chimney: ${vars.base} {
  name: "chimney"
  uri: "https://github.com/scalalandio/chimney.git#d37facc384d0149c3fec4d6670c37db6873c1afb"

  extra.exclude: ["*3", "*2_12", "*JS", "*Native", "benchmarks", "chimneySandwichTests"]
  extra.commands: ${vars.default-commands} [
    "appendScalacOptions -Xsource-features:eta-expand-always"
  ]
}
