// https://github.com/circe/circe-generic-extras.git#main

vars.proj.circe-generic-extras: ${vars.base} {
  name: "circe-generic-extras"
  uri: "https://github.com/circe/circe-generic-extras.git#5a40ade9d203dd2ec95261e29f226fb7718e9b9a"

  extra.projects: ["genericExtrasJVM"]
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.14""""
  ]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    // so we don't have to arrange for dbuild-built semanticdb to be brought in
    "set every semanticdbEnabled := false"
  ]
}
