// https://github.com/circe/circe-generic-extras.git#main

vars.proj.circe-generic-extras: ${vars.base} {
  name: "circe-generic-extras"
  uri: "https://github.com/circe/circe-generic-extras.git#3c9488ed805a58354f07e897c437589cfae6b953"

  extra.projects: ["genericExtrasJVM"]
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.14""""
  ]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    // so we don't have to arrange for dbuild-built semanticdb to be brought in
    "set every semanticdbEnabled := false"
  ]
}
