// https://github.com/vlovgr/ciris.git#master

vars.proj.ciris: ${vars.base} {
  name: "ciris"
  uri: "https://github.com/vlovgr/ciris.git#ea321cb67227a1291ef28313794b137a9c6d9b3f"

  extra.exclude: ["docs", "*JS", "*Native"]
}
