// https://github.com/vlovgr/ciris.git#master

vars.proj.ciris: ${vars.base} {
  name: "ciris"
  uri: "https://github.com/vlovgr/ciris.git#3b164bb97e10c25e1e66f78924dc5eb0d7a3b4fe"

  extra.exclude: ["docs", "*JS", "*Native"]
}
