// https://github.com/vlovgr/ciris.git#master

vars.proj.ciris: ${vars.base} {
  name: "ciris"
  uri: "https://github.com/vlovgr/ciris.git#5a463ae226ad41ce522f77dd6b0c65bea5efbf97"

  extra.exclude: ["docs", "*JS", "*Native"]
}
