// https://github.com/erikerlandson/coulomb.git#scala2

// Stress-test of implicit chaining improvements from
// https://github.com/scala/scala/pull/6050

vars.proj.coulomb: ${vars.base} {
  name: "coulomb"
  uri: "https://github.com/erikerlandson/coulomb.git#101ecabbba468424c46a33104ea92a3e439ecf3d"

  extra.projects: ["coulomb_testsJVM"] // builds & tests everything.... I think
  extra.commands: ${vars.default-commands} [
    // don't ask for passphrase when running locally
    "set every gpgWarnOnFailure := true"
    // prevent sbt-gpg from asking for passphrase when running locally
    """set every gpgKey := Some("")"""
  ]
}
