// https://github.com/Chymyst/curryhoward.git#master

vars.proj.curryhoward: ${vars.base} {
  name: "curryhoward"
  uri: "https://github.com/Chymyst/curryhoward.git#52b591c1a5eda00ac0589bed6ad552adb8dda998"

}
