// https://github.com/alexarchambault/data-class.git#main

vars.proj.data-class: ${vars.base} {
  name: "data-class"
  uri: "https://github.com/alexarchambault/data-class.git#0017c4208bebddee1bec04130d3da56783d93244"

  // the repo's .travis.yml does the following:
  //   test test-proj-v1/publishLocal test-proj-v2/mimaReportBinaryIssues proj-v1-user/compile
  // I think trying to do something like in this in the dbuild context is probably more trouble
  // than it's actually worth
  extra.exclude: ["test-proj-*"]
  // exclude a test, pending outcome of https://github.com/scala/scala-dev/issues/928
  extra.commands: ${vars.default-commands} [
    """set `data-class` / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "OneFieldTests.scala""""
  ]
}
