// https://github.com/alexarchambault/data-class.git#main

vars.proj.data-class: ${vars.base} {
  name: "data-class"
  uri: "https://github.com/alexarchambault/data-class.git#4ba06af66df39c955ab7c97050837ba1a1db841d"

  // the repo's .travis.yml does the following:
  //   test test-proj-v1/publishLocal test-proj-v2/mimaReportBinaryIssues proj-v1-user/compile
  // I think trying to do something like in this in the dbuild context is probably more trouble
  // than it's actually worth
  extra.exclude: ["test-proj-*"]
}
