// https://github.com/bkirwi/decline.git#main

vars.proj.decline: ${vars.base} {
  name: "decline"
  uri: "https://github.com/bkirwi/decline.git#8dc0320e12c19015ab46a1f65547d460e62a5144"

  extra.projects: ["declineJVM", "refinedJVM"]  // no Scala.js, no doc
}
