// https://github.com/bkirwi/decline.git#main

vars.proj.decline: ${vars.base} {
  name: "decline"
  uri: "https://github.com/bkirwi/decline.git#e7325acea93ec9b9e54c69d36067d1fdfe0b787f"

  extra.projects: ["declineJVM", "refinedJVM"]  // no Scala.js, no doc
}
