// https://github.com/bkirwi/decline.git#main

vars.proj.decline: ${vars.base} {
  name: "decline"
  uri: "https://github.com/bkirwi/decline.git#f61c6b02413b763480987441e870bd94c65cac50"

  extra.projects: ["declineJVM", "refinedJVM"]  // no Scala.js, no doc
}
