// https://github.com/jatcwang/difflicious.git#master

vars.proj.difflicious: ${vars.base} {
  name: "difflicious"
  uri: "https://github.com/jatcwang/difflicious.git#2a47cba598003a24a5feda97e169856c35d288eb"

  extra.exclude: ["docs", "benchmarks", "*3", "*JS", "*Native"]
}
