// https://github.com/jatcwang/difflicious.git#master

vars.proj.difflicious: ${vars.base} {
  name: "difflicious"
  uri: "https://github.com/jatcwang/difflicious.git#f8dc28aa6216edfd66f96db16c9bc4cac8d337ad"

  extra.exclude: ["docs", "benchmarks", "*3", "*JS", "*Native"]
}
