// https://github.com/jatcwang/difflicious.git#master

vars.proj.difflicious: ${vars.base} {
  name: "difflicious"
  uri: "https://github.com/jatcwang/difflicious.git#919ea68ae8dedad45d7a00e3c8d0b50eaded293b"

  extra.exclude: ["docs", "benchmarks", "*3"]
}
