// https://github.com/typelevel/discipline-scalatest.git#main

vars.proj.discipline-scalatest: ${vars.base} {
  name: "discipline-scalatest"
  uri: "https://github.com/typelevel/discipline-scalatest.git#0cb8dc957446e4c64fe3264e1463aa8526d43435"

  extra.exclude: ["*JS", "*Native", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
  ]
}
