// https://github.com/typelevel/discipline-specs2.git#main

vars.proj.discipline-specs2: ${vars.base} {
  name: "discipline-specs2"
  uri: "https://github.com/typelevel/discipline-specs2.git#6c1e34c42293a136989a93b88774a617f509675a"

  extra.exclude: ["*JS", "*Native", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
  ]
}
