// https://github.com/typelevel/discipline-scalatest.git#main

vars.proj.discipline-scalatest: ${vars.base} {
  name: "discipline-scalatest"
  uri: "https://github.com/typelevel/discipline-scalatest.git#0a759c6a1b4d3bdb443612c6163503f7fb36fe23"

  extra.exclude: ["*JS", "*Native", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
  ]
}
