// https://github.com/typelevel/discipline-specs2.git#main

vars.proj.discipline-specs2: ${vars.base} {
  name: "discipline-specs2"
  uri: "https://github.com/typelevel/discipline-specs2.git#3ef47185f127110e74979684dcfad0652a6a86a0"

  extra.exclude: ["*JS", "*Native", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
  ]
}
