// https://github.com/typelevel/discipline-munit.git#main

vars.proj.discipline-munit: ${vars.base} {
  name: "discipline-munit"
  uri: "https://github.com/typelevel/discipline-munit.git#eeb871bce6301c7616ed6f95b4e0f4c22865b43a"

  extra.exclude: ["*JS", "*Native"]
}
