// https://github.com/typelevel/discipline-specs2.git#main

vars.proj.discipline-specs2: ${vars.base} {
  name: "discipline-specs2"
  uri: "https://github.com/typelevel/discipline-specs2.git#de3faf3d9a1e147c029bf64d78336e055eba9426"

  extra.exclude: ["*JS", "*Native", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
  ]
}
