// https://github.com/typelevel/discipline.git#main

vars.proj.discipline: ${vars.base} {
  name: "discipline"
  uri: "https://github.com/typelevel/discipline.git#f5ef564b9e6b2e745872827b2b568e0e84e82a24"

  extra.projects: ["coreJVM"]  // no Scala.js please
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
  extra.commands: ${vars.default-commands} [
    // "Credentials file [...] does not exist"
    "set every credentials := Seq()"
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
