// https://github.com/typelevel/discipline-munit.git#main

vars.proj.discipline-munit: ${vars.base} {
  name: "discipline-munit"
  uri: "https://github.com/typelevel/discipline-munit.git#e54a7492d32d017c23aea62c2e59a1e99b9eceeb"

  extra.exclude: ["*JS", "*Native"]
}
