// https://github.com/typelevel/discipline-scalatest.git#main

vars.proj.discipline-scalatest: ${vars.base} {
  name: "discipline-scalatest"
  uri: "https://github.com/typelevel/discipline-scalatest.git#555d933d28aab670216f8157e629ed5e48462de4"

  extra.exclude: ["*JS", "*Native", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
  ]
}
