// https://github.com/typelevel/discipline-munit.git#main

vars.proj.discipline-munit: ${vars.base} {
  name: "discipline-munit"
  uri: "https://github.com/typelevel/discipline-munit.git#4083e7157a4001a8710dc7de7f2e361ef43755e3"

  extra.exclude: ["*JS", "*Native"]
}
