// https://github.com/atnos-org/eff.git#master

vars.proj.eff: ${vars.base} {
  name: "eff"
  uri: "https://github.com/atnos-org/eff.git#c032cd58213782db6411d69348bb258e5d0ecd0c"

  extra.exclude: ["scalazJVM", "*JS", "*Native"]
}
