// https://github.com/atnos-org/eff.git#master

vars.proj.eff: ${vars.base} {
  name: "eff"
  uri: "https://github.com/atnos-org/eff.git#4be91fea98f697252756c3c6f781101ecdb8a559"

  extra.exclude: ["scalazJVM", "*JS", "*Native"]
}
