// https://github.com/atnos-org/eff.git#master

vars.proj.eff: ${vars.base} {
  name: "eff"
  uri: "https://github.com/atnos-org/eff.git#d177df7aa5a4faec5faee243f885221c00aa66f7"

  extra.exclude: ["scalazJVM", "*JS", "*Native"]
}
