// https://github.com/eed3si9n/expecty.git#develop

// dependency of scopt

vars.proj.expecty: ${vars.base} {
  name: "expecty"
  uri: "https://github.com/eed3si9n/expecty.git#49cd4a356106b65d9b2dfc965a3e6866dcd4a14a"

  extra.projects: ["expecty2_12"]
  extra.settings: ${vars.base.extra.settings} [
    "Global / semanticdbEnabled := false"
  ]
}
