// https://github.com/eed3si9n/expecty.git#develop

// dependency of scopt

vars.proj.expecty: ${vars.base} {
  name: "expecty"
  uri: "https://github.com/eed3si9n/expecty.git#88caad9332eb1a2a3195e00d961719679466ea64"

  extra.projects: ["expecty2_12"]
  extra.settings: ${vars.base.extra.settings} [
    "Global / semanticdbEnabled := false"
  ]
}
