// https://github.com/eed3si9n/expecty.git#develop

// dependency of scopt

vars.proj.expecty: ${vars.base} {
  name: "expecty"
  uri: "https://github.com/eed3si9n/expecty.git#f027387c61ef4e7fc40f4e017494f8b657a0f472"

  extra.projects: ["expecty2_12"]
  extra.settings: ${vars.base.extra.settings} [
    "Global / semanticdbEnabled := false"
  ]
}
