// https://github.com/plokhotnyuk/expression-evaluator.git#master

vars.proj.expression-evaluator: ${vars.base} {
  name: "expression-evaluator"
  uri: "https://github.com/plokhotnyuk/expression-evaluator.git#c3cc53c70ea1467af83a389c180765a0e803f86d"

  extra.settings: ${vars.base.extra.settings} [
    // resolve version conflict (from sbt-scoverage, probably?)
    // one-deeper nesting level makes it apply to build definition
    ["""ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always"""]
  ]
}
