// https://github.com/plokhotnyuk/expression-evaluator.git#master

vars.proj.expression-evaluator: ${vars.base} {
  name: "expression-evaluator"
  uri: "https://github.com/plokhotnyuk/expression-evaluator.git#e97499534f0b71804ba0fcd4e57eefc910d7897f"

  extra.settings: ${vars.base.extra.settings} [
    // resolve version conflict (from sbt-scoverage, probably?)
    // one-deeper nesting level makes it apply to build definition
    ["""ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always"""]
  ]
}
