// https://github.com/typelevel/fabric.git#master

vars.proj.fabric: ${vars.base} {
  name: "fabric"
  uri: "https://github.com/typelevel/fabric.git#ea22ed959eea1865cac0c86bdd13d59fae6c530c"

  extra.projects: ["*JVM"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
