// https://github.com/typelevel/fabric.git#master

vars.proj.fabric: ${vars.base} {
  name: "fabric"
  uri: "https://github.com/typelevel/fabric.git#799f5e52b9f004e89b5f42230130fdf2919151d8"

  extra.projects: ["*JVM"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
