// https://github.com/typelevel/fabric.git#master

vars.proj.fabric: ${vars.base} {
  name: "fabric"
  uri: "https://github.com/typelevel/fabric.git#9ca6c933433b77bf8691675b0b6d027be0876bcc"

  extra.projects: ["*JVM"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
