// https://github.com/fastscala/fastscala.git#main

vars.proj.fastscala: ${vars.base} {
  name: "fastscala"
  uri: "https://github.com/fastscala/fastscala.git#4b4f80542b4c98df72dd2423f0a6a90b30cc1d9b"

  extra.commands: ${vars.default-commands} [
    // these tests appear to require a postgres instance, so we only compile them
    "set fs_db / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
  ]
}
