// https://github.com/fastscala/fastscala.git#main

vars.proj.fastscala: ${vars.base} {
  name: "fastscala"
  uri: "https://github.com/fastscala/fastscala.git#e1ec99d7eb49604f78a3f8c5a8d738d5fa12cccc"

  // we could enable these if this ticket gets addressed:
  // https://github.com/fastscala/fastscala/issues/7
  extra.exclude: ["fs_db", "fs_taskmanager"]
}
