// https://github.com/fastscala/fastscala.git#1ce523b393045d842e414b7759811e26e3017c20  # was main

// frozen (December 2024) because the repo is on Scala 3 now

vars.proj.fastscala: ${vars.base} {
  name: "fastscala"
  uri: "https://github.com/fastscala/fastscala.git#1ce523b393045d842e414b7759811e26e3017c20"

  extra.commands: ${vars.default-commands} [
    // these tests appear to require a postgres instance, so we only compile them
    "set fs_db / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
  ]
}
