// https://github.com/finagle/finch.git#master

vars.proj.finch: ${vars.base} {
  name: "finch"
  uri: "https://github.com/finagle/finch.git#70162cda762a6037f7c0f85042b78df05d641d5a"

  extra.exclude: ["benchmarks", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every semanticdbEnabled := false"
    "set every scalafixOnCompile := false"
    "set every scalafmtOnCompile := false"
  ]
}
