// https://github.com/finagle/finch.git#master

vars.proj.finch: ${vars.base} {
  name: "finch"
  uri: "https://github.com/finagle/finch.git#2e4b67b0112e5e49dca7bbb815227279ad096f59"

  extra.exclude: ["benchmarks", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every semanticdbEnabled := false"
    "set every scalafixOnCompile := false"
    "set every scalafmtOnCompile := false"
  ]
}
