// https://github.com/finagle/finch.git#master

vars.proj.finch: ${vars.base} {
  name: "finch"
  uri: "https://github.com/finagle/finch.git#de15be02da52490fe78f97fe6a0de1839cdd509d"

  extra.exclude: ["benchmarks", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every semanticdbEnabled := false"
    "set every scalafixOnCompile := false"
    "set every scalafmtOnCompile := false"
  ]
}
