// https://github.com/scalacommunitybuild/formless.git#community-build-2.13  # was mblink, main

// forked (February 2025) to remove the need for a custom resolver
// for a publishing plugin. we could add the resolver to our Artifactory
// but I have chosen the lower-effort route of forking

vars.proj.formless: ${vars.base} {
  name: "formless"
  uri: "https://github.com/scalacommunitybuild/formless.git#c397613de0efa9ed04caceb4517514f71fbce1ea"

  extra.exclude: ["docs", "*JS", "*Native"]
}
