// https://github.com/typelevel/fs2.git#series/3.12

// we could track main instead, I suppose? 3.12.x is the current
// release series as of October 2025

vars.proj.fs2: ${vars.base} {
  name: "fs2"
  uri: "https://github.com/typelevel/fs2.git#46e2dc3abf994dcf3d0b804b2ddb3c10c04d4976"

  extra.exclude: ["*JS", "*Native", "benchmark", "microsite", "unidocs"]
  extra.options: ["-Xmx4g"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
