// https://github.com/typelevel/fs2.git#main

vars.proj.fs2: ${vars.base} {
  name: "fs2"
  uri: "https://github.com/typelevel/fs2.git#ad8c6f3a0d2859247c3fc2d2cc32bc3016272f03"

  extra.exclude: ["*JS", "*Native", "benchmark", "microsite", "unidocs"]
  extra.options: ["-Xmx4g"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
    // not investigated
    """set integration / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "MemoryLeakSpec.scala""""
    // chews up excessive disk space in /tmp (issue #1734)
    """set io.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "WalkBenchmark.scala""""
  ]
}
