// https://github.com/lightbend/genjavadoc.git#main

vars.proj.genjavadoc: ${vars.base} {
  name: "genjavadoc"
  uri: "https://github.com/lightbend/genjavadoc.git#2097cdde57ae1d4f73e866bc1e7408330dacb1a1"

}
