// https://github.com/lightbend/genjavadoc.git#main

vars.proj.genjavadoc: ${vars.base} {
  name: "genjavadoc"
  uri: "https://github.com/lightbend/genjavadoc.git#82b67d43c383043d10a704270b75851efce101b0"

}
