// https://github.com/lightbend/genjavadoc.git#main

vars.proj.genjavadoc: ${vars.base} {
  name: "genjavadoc"
  uri: "https://github.com/lightbend/genjavadoc.git#6254eb7276808147659e24baddbecc2e5265e1f6"

}
