// https://github.com/http4s/http4s.git#main

vars.proj.http4s: ${vars.base} {
  name: "http4s"
  uri: "https://github.com/http4s/http4s.git#c63fbff43dfe7e3bec25b789fd0a0027ec40ed62"

  extra.options: ["-Xmx6g"]  // match .jvmopts in repo
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    // don't ask for passphrase when running locally
    """set every gpgKey := Some("")"""
    // java.net.ConnectException on all of these
    """set client.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "JavaNetClientSuite.scala""""
    """set emberClient.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "EmberClientSuite.scala""""
    // EmberUnixSocketSuite: javax.net.ssl.SSLHandshakeException: Empty server certificate chain
    // EmberServerMtlsSuite: fails on JDK 26
    """set emberServer.jvm / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "EmberUnixSocketSuite.scala" || "EmberServerMtlsSuite.scala""""
  ]
  extra.exclude: [
    "root*", "*JS", "*Native", "bench", "js-artifact-size-test"
  ]
}
