// https://github.com/Comcast/ip4s.git#main

vars.proj.ip4s: ${vars.base} {
  name: "ip4s"
  uri: "https://github.com/Comcast/ip4s.git#c823107530fc43013982f40f1b8072260e43d569"

  extra.exclude: ["*JS", "*Native"]
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
  ]
}
