// https://github.com/lightbend-labs/jardiff.git#main

vars.proj.jardiff: ${vars.base} {
  name: "jardiff"
  uri: "https://github.com/lightbend-labs/jardiff.git#8134d50170affa7e8c3544824757b29ae61e0ac0"

}
