// https://github.com/scala-garden/jardiff.git#main

vars.proj.jardiff: ${vars.base} {
  name: "jardiff"
  uri: "https://github.com/scala-garden/jardiff.git#20745890eff8447b4d8ed23c04f588f80b48919d"

}
