// https://github.com/lightbend-labs/jardiff.git#main

vars.proj.jardiff: ${vars.base} {
  name: "jardiff"
  uri: "https://github.com/lightbend-labs/jardiff.git#e608274f53d2bbf17664e6ac68c6423643a75f0f"

}
