// https://github.com/typelevel/jawn.git#main

vars.proj.jawn: ${vars.base} {
  name: "jawn"
  uri: "https://github.com/typelevel/jawn.git#bf7ab50500c9c01de41391828029d45f15c45bba"

  extra.exclude: ["*JS", "*Native", "benchmark", "root"]
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
