// https://github.com/typelevel/jawn.git#main

vars.proj.jawn: ${vars.base} {
  name: "jawn"
  uri: "https://github.com/typelevel/jawn.git#bd94ac9e5b88571565eb1b9dd20bc7a5bf24a022"

  extra.exclude: ["*JS", "*Native", "benchmark", "root"]
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
