// https://github.com/typelevel/jawn.git#main

vars.proj.jawn: ${vars.base} {
  name: "jawn"
  uri: "https://github.com/typelevel/jawn.git#520099ea0bc62789e655938ebaa99239122e3b08"

  extra.exclude: ["*JS", "*Native", "benchmark", "root"]
  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
