// https://github.com/json4s/json4s.git#master

vars.proj.json4s: ${vars.base} {
  name: "json4s"
  uri: "https://github.com/json4s/json4s.git#95196d63e280a1e2227082332d18a2f9f67a84b7"

  extra.projects: ["*JVM2_13"]
  extra.commands: ${vars.default-commands} [
    "appendScalacOptions -Wconf:cat=scala3-migration:w"
  ]
}
