// https://github.com/json4s/json4s.git#master

vars.proj.json4s: ${vars.base} {
  name: "json4s"
  uri: "https://github.com/json4s/json4s.git#9ed5510e3a9d42e52f19d20d56db5327496aa44e"

  extra.projects: ["*JVM2_13"]
  extra.commands: ${vars.default-commands} [
    "appendScalacOptions -Wconf:cat=scala3-migration:w"
  ]
}
