// https://github.com/json4s/json4s.git#master

vars.proj.json4s: ${vars.base} {
  name: "json4s"
  uri: "https://github.com/json4s/json4s.git#c8e7672902157411dc5d25485f93c11c90a8c666"

  extra.projects: ["*JVM2_13"]
  extra.commands: ${vars.default-commands} [
    "appendScalacOptions -Wconf:cat=scala3-migration:w"
  ]
}
