// https://github.com/kamon-io/Kamon.git#master

vars.proj.kamon: ${vars.base} {
  name: "kamon"
  uri: "https://github.com/kamon-io/Kamon.git#a376f39873921a1b2def82942e06950756522307"

  // just what lila-ws needs, for now anyway
  extra.projects: ["kamon-core", "kamon-influxdb", "kamon-system-metrics"]
}
