// https://github.com/kamon-io/Kamon.git#master

vars.proj.kamon: ${vars.base} {
  name: "kamon"
  uri: "https://github.com/kamon-io/Kamon.git#a6dd3c3e8e43c1b8a0e8c95bfc4c145b2354eb1c"

  // just what lila-ws needs, for now anyway
  extra.projects: ["kamon-core", "kamon-influxdb", "kamon-system-metrics"]
}
