// https://github.com/kamon-io/Kamon.git#master

vars.proj.kamon: ${vars.base} {
  name: "kamon"
  uri: "https://github.com/kamon-io/Kamon.git#f4898d98937f2c19be0784dcd3c9efd80f639e93"

  // just what lila-ws needs, for now anyway
  extra.projects: ["kamon-core", "kamon-influxdb", "kamon-system-metrics"]
}
