// https://github.com/typelevel/kittens.git#master

vars.proj.kittens: ${vars.base} {
  name: "kittens"
  uri: "https://github.com/typelevel/kittens.git#f56878855470eca491111f20c6c3ffbdeb22206b"

  extra.projects: ["coreJVM"]  // sorry, Scala.js
}
