// https://github.com/typelevel/kittens.git#master

vars.proj.kittens: ${vars.base} {
  name: "kittens"
  uri: "https://github.com/typelevel/kittens.git#55bd9acbed8f228f345ebae8376635a5974a92f5"

  extra.projects: ["coreJVM"]  // sorry, Scala.js
}
