// https://github.com/typelevel/kittens.git#master

vars.proj.kittens: ${vars.base} {
  name: "kittens"
  uri: "https://github.com/typelevel/kittens.git#f9486dadbc7622d55ffa16b5731b820aae465d7b"

  extra.projects: ["coreJVM"]  // sorry, Scala.js
}
