// https://github.com/lightbend-labs/lightbend-emoji.git#main

vars.proj.lightbend-emoji: ${vars.base} {
  name: "lightbend-emoji"
  uri: "https://github.com/lightbend-labs/lightbend-emoji.git#44811bf040b11744a1652568bc6430d9f4c5dc07"

  extra.options: ["-Dsbt.sbtbintray=false"]
}
