// https://github.com/lightbend-labs/lightbend-emoji.git#main

vars.proj.lightbend-emoji: ${vars.base} {
  name: "lightbend-emoji"
  uri: "https://github.com/lightbend-labs/lightbend-emoji.git#a7de7e1917e24cfec59578fa0f390ce82ad166c5"

  extra.options: ["-Dsbt.sbtbintray=false"]
}
