// https://github.com/lightbend-labs/lightbend-emoji.git#main

vars.proj.lightbend-emoji: ${vars.base} {
  name: "lightbend-emoji"
  uri: "https://github.com/lightbend-labs/lightbend-emoji.git#a306ce0494be6a0792794fc2693821942b9a7d46"

  extra.options: ["-Dsbt.sbtbintray=false"]
}
