// https://github.com/ChristopherDavenport/log4cats.git#main

vars.proj.log4cats: ${vars.base} {
  name: "log4cats"
  uri: "https://github.com/ChristopherDavenport/log4cats.git#4a9142260382a4e4ee5e4c793ee3691bb44bef77"

  extra.exclude: [
    "docs", "*JS", "*Native", "js-console"
    "slf4j" // wants coreJS for some reason
  ]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
