// https://github.com/ChristopherDavenport/log4cats.git#main

vars.proj.log4cats: ${vars.base} {
  name: "log4cats"
  uri: "https://github.com/ChristopherDavenport/log4cats.git#15dbc46bc0cdae5cf3ca3e5956bebe3a1fd3b38a"

  extra.exclude: [
    "docs", "*JS", "*Native", "js-console"
    "slf4j" // wants coreJS for some reason
  ]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
