// https://github.com/scalamacros/paradise.git#2.12.8

vars.proj.macro-paradise = ${vars.base} {
  name: "macro-paradise"
  uri: "https://github.com/scalamacros/paradise.git#a631888893a193e6a58584f2a0db4dc30a7935cf"

  extra.options: [
    // because ScaladocSuite calls setSecurityManager
    ${?SECURITY_MANAGER}
  ]
}
