// https://github.com/softwaremill/macwire.git#master

vars.proj.macwire: ${vars.base} {
  name: "macwire"
  uri: "https://github.com/softwaremill/macwire.git#82302419a79dbfe2710973486fe6727e16007ca1"

  extra.exclude: ["*2_12", "*JS", "*3", "*Native"]
}
