// https://github.com/softwaremill/macwire.git#master

vars.proj.macwire: ${vars.base} {
  name: "macwire"
  uri: "https://github.com/softwaremill/macwire.git#d0ef11a27a2d6fd1f0cee103bb80f47abb35a5a2"

  extra.exclude: ["*2_12", "*JS", "*3", "*Native"]
}
