// https://github.com/softwaremill/macwire.git#master

vars.proj.macwire: ${vars.base} {
  name: "macwire"
  uri: "https://github.com/softwaremill/macwire.git#2cbe554fb152dea6e76a3c84fbca6908ee0d0724"

  extra.exclude: ["*2_12", "*JS", "*3", "*Native"]
}
