// https://github.com/softwaremill/magnolia.git#scala2

vars.proj.magnolia: ${vars.base} {
  name: "magnolia"
  uri: "https://github.com/softwaremill/magnolia.git#6d0bd3eb471804993ab9dbe1b5582d04ba4ed097"

  extra.exclude: ["*2_12", "*JS", "*Native"]
}
