// https://github.com/softwaremill/magnolia.git#scala2

vars.proj.magnolia: ${vars.base} {
  name: "magnolia"
  uri: "https://github.com/softwaremill/magnolia.git#47391b11d0de244649b059267bfdd4f5e4adb519"

  extra.exclude: ["*2_12", "*JS", "*Native"]
}
