// https://github.com/softwaremill/magnolia.git#scala2

vars.proj.magnolia: ${vars.base} {
  name: "magnolia"
  uri: "https://github.com/softwaremill/magnolia.git#8cf9508ea2b0da9baecc78fd5fde81abb9b1418c"

  extra.exclude: ["*2_12", "*JS", "*Native"]
}
