// https://github.com/scalameta/mdoc.git#main

vars.proj.mdoc: ${vars.base} {
  name: "mdoc"
  uri: "https://github.com/scalameta/mdoc.git#a0e3e6501057d6ddfd63db37828b9d4123224ce7"

  extra.exclude: [
    "js*", "docs", "unit", "plugin", "*JS", "*Native"
    // tests-only, and it downloads Maven Central artifacts but doesn't use the right Scala binary version.
    // probably not worth tinkering with
    "worksheets"
  ]
}
