// https://github.com/scalameta/mdoc.git#main

vars.proj.mdoc: ${vars.base} {
  name: "mdoc"
  uri: "https://github.com/scalameta/mdoc.git#3bb54acb22f6f25c8e1b46df994fd7b68f7c3ff9"

  extra.exclude: [
    "js*", "docs", "unit", "plugin", "*JS", "*Native"
    // tests-only, and it downloads Maven Central artifacts but doesn't use the right Scala binary version.
    // probably not worth tinkering with
    "worksheets"
  ]
}
