// https://github.com/scalameta/mdoc.git#main

vars.proj.mdoc: ${vars.base} {
  name: "mdoc"
  uri: "https://github.com/scalameta/mdoc.git#d356874f2a0aff98063236f6a4bc57cd0ddb5a90"

  extra.exclude: [
    "js*", "docs", "unit", "plugin", "*JS", "*Native"
    // tests-only, and it downloads Maven Central artifacts but doesn't use the right Scala binary version.
    // probably not worth tinkering with
    "worksheets"
  ]
}
