// https://github.com/scalameta/metaconfig.git#main

vars.proj.metaconfig: ${vars.base} {
  name: "metaconfig"
  uri: "https://github.com/scalameta/metaconfig.git#ad5d3178675b13a105333e230518671c9a44ef76"

  extra.exclude: [
    "*JS", "*Native"
    // it's sad not to run the tests. but testsJVM depends on docs, and testsJVM
    // does yarn stuff that failed on jenkins, and locally it ran into
    // weird conflicting cross-version errors in dbuild.  oh well -- we have
    // the repo primarily because scalafix and scalafmt need it, anyway.
    "testsJVM", "docs"
   ]
}
