// https://github.com/scalameta/metals.git#main

// note that there are always test failures when we run on a PR validation
// snapshot. (we could probably fix it by adding a resolver in the repo?)

// for reproducing failures outside of dbuild, you need to locally publish
// scalameta. in the metals repo after `++2.13.xx-bin-abc123!`, `Test/update`
// will show you what scalameta version is expected. suppose it's 4.5.6.
// then you go to the scalameta repo and do:
//   * git checkout v4.5.6
//   * sbt
//   * ++2.13.xx-bin-abc123!
//   * set every version := "4.5.6"
//   * semanticdbScalacCore/publishLocal
//   * semanticdbScalacPlugin/publishLocal

vars.proj.metals: ${vars.base} {
  name: "metals"
  uri: "https://github.com/scalameta/metals.git#06f3d13b959d2ea8b46b3f5b79d92ce1dd0f70e2"

  extra.options: ["-Xmx3g"]
  // Vadim from Virtus writes:
  //
  // > it would be better to include only `mtags` and `cross` subprojects of metals build.
  // > and run tests only for cross.
  // > Metals itself and it's other test-suprojects have some flaky
  // > tests + some tests data highly depends on scala-compiler version and
  // > might lead to false-positive failures
  //
  // At present, the net here is cast wider than that, but it's advice to keep
  // in mind if we start having problems with any of the other subprojects.
  // (As always, one option is to compile some tests but not run them.)
  extra.exclude: [
    "metals", "sbt-metals", "input3", "bench", "docs", "slow"
    // this depends on input3
    "unit"
    // I don't know what this is for but it's been giving us a
    // conflicting cross-version suffixes error and I don't think we need it
    "metalsDependencies"
  ]
}
