// https://github.com/scalameta/metals.git#main

// note that there are always test failures when we run on a PR validation
// snapshot. (we could probably fix it by adding a resolver in the repo?)

// for reproducing failures outside of dbuild, you need to locally publish
// scalameta. in the metals repo after `++2.13.xx-bin-abc123!`, `Test/update`
// will show you what scalameta version is expected. suppose it's 4.5.6.
// then you go to the scalameta repo and do:
//   * ++2.13.xx-bin-abc123!
//   * git checkout v4.5.6
//   * set every version := "4.5.6"
//   * semanticdbScalacCore/publishLocal
//   * semanticdbScalacPlugin/publishLocal

vars.proj.metals: ${vars.base} {
  name: "metals"
  uri: "https://github.com/scalameta/metals.git#66321e4b1268625d588fb64cc181fb9fa4a7ffe5"

  extra.options: ["-Xmx3g"]
  // Vadim from Virtus writes:
  //
  // > it would be better to include only `mtags` and `cross` subprojects of metals build.
  // > and run tests only for cross.
  // > Metals itself and it's other test-suprojects have some flaky
  // > tests + some tests data highly depends on scala-compiler version and
  // > might lead to false-positive failures
  //
  // At present, the net here is cast wider than that, but it's advice to keep
  // in mind if we start having problems with any of the other subprojects.
  // (As always, one option is to compile some tests but not run them.)
  extra.exclude: [
    "metals", "sbt-metals", "input3", "bench", "docs", "slow"
    // this depends on input3
    "unit"
  ]
  extra.commands: ${vars.default-commands} [
    // HoverTermSuite: https://github.com/scalameta/metals/issues/5318
    """set javapc / unmanagedSources / excludeFilter := HiddenFileFilter || "HoverTermSuite.scala""""
    // we should be able to remove this once they take the 2.13.17 upgrade
    """set cross / unmanagedSources / excludeFilter := HiddenFileFilter || "SignatureHelpDocSuite.scala""""
  ]
}
