// https://github.com/erikvanoosten/metrics-scala.git#master

vars.proj.metrics-scala: ${vars.base} {
  name: "metrics-scala"
  uri: "https://github.com/erikvanoosten/metrics-scala.git#57defcc3586661ec269a5fe7f0e227a4ed0bbad1"

}
