// https://github.com/erikvanoosten/metrics-scala.git#master

vars.proj.metrics-scala: ${vars.base} {
  name: "metrics-scala"
  uri: "https://github.com/erikvanoosten/metrics-scala.git#65177407f6ca2c1ae687e19c2e06f720babcd3c3"

}
