// https://github.com/erikvanoosten/metrics-scala.git#master

vars.proj.metrics-scala: ${vars.base} {
  name: "metrics-scala"
  uri: "https://github.com/erikvanoosten/metrics-scala.git#1ef5f7ad7fa277c17c78d30b8b5f1b47508fab5d"

}
