// https://github.com/monix/minitest.git#master

vars.proj.minitest: ${vars.base} {
  name: "minitest"
  uri: "https://github.com/monix/minitest.git#903dfa3bdb08fc5adbd8cf90b546094a03fb329e"

  extra.projects: ["minitestJVM", "lawsJVM"]  // no Scala.js
}
