// https://github.com/mockito/mockito-scala.git#release/1.x

vars.proj.mockito-scala: ${vars.base} {
  name: "mockito-scala"
  uri: "https://github.com/mockito/mockito-scala.git#e5a465de8c5d58fffa6853b0e687bc52bee936e9"

  extra.exclude: ["scalaz"]
}
