// https://github.com/julien-truffaut/Monocle.git#master

vars.proj.monocle: ${vars.base} {
  name: "monocle"
  uri: "https://github.com/julien-truffaut/Monocle.git#6c203ae178701ab98dae9755aa76f3d9b2ed47fb"

  // try to enable more subprojects?
  extra.projects: ["coreJVM", "macrosJVM", "lawJVM", "genericJVM"]
}
