// https://github.com/typelevel/mouse.git#main

vars.proj.mouse: ${vars.base} {
  name: "mouse"
  uri: "https://github.com/typelevel/mouse.git#526ae3df7cea4252df1c14ba3ccf0de3ffae75f6"

  extra.projects: ["crossJVM"]  // no Scala.js please
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
