// https://github.com/typelevel/mouse.git#main

vars.proj.mouse: ${vars.base} {
  name: "mouse"
  uri: "https://github.com/typelevel/mouse.git#f6469b541e41a434d19078be2c57958af8d11d94"

  extra.projects: ["crossJVM"]  // no Scala.js please
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
