// https://github.com/typelevel/mouse.git#main

vars.proj.mouse: ${vars.base} {
  name: "mouse"
  uri: "https://github.com/typelevel/mouse.git#aeb70e9aec48b4314d58bdc92e9938324ec2b5bd"

  extra.projects: ["crossJVM"]  // no Scala.js please
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
