// https://github.com/scalameta/munit-scalacheck.git#main

vars.proj.munit-scalacheck: ${vars.base} {
  name: "munit-scalacheck"
  uri: "https://github.com/scalameta/munit-scalacheck.git#cd1458586031d414d4c1ca0e22eac3f82b24b159"

  extra.exclude: ["*JS", "*Native"]
}
