// https://github.com/typelevel/munit-cats-effect.git#main

vars.proj.munit-cats-effect: ${vars.base} {
  name: "munit-cats-effect"
  uri: "https://github.com/typelevel/munit-cats-effect.git#84c216af175f9fc112a285705dc20fce5414aaba"

  extra.exclude: ["docs", "*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
