// https://github.com/scalameta/munit-scalacheck.git#main

vars.proj.munit-scalacheck: ${vars.base} {
  name: "munit-scalacheck"
  uri: "https://github.com/scalameta/munit-scalacheck.git#59fb3401579181c6caef4069bcf4d4fcddc44149"

  extra.exclude: ["*JS", "*Native"]
}
