// https://github.com/scalameta/munit-scalacheck.git#main

vars.proj.munit-scalacheck: ${vars.base} {
  name: "munit-scalacheck"
  uri: "https://github.com/scalameta/munit-scalacheck.git#acbbf99f3943fd43e404eac962643647ee774459"

  extra.exclude: ["*JS", "*Native"]
}
