// https://github.com/typelevel/munit-cats-effect.git#main

vars.proj.munit-cats-effect: ${vars.base} {
  name: "munit-cats-effect"
  uri: "https://github.com/typelevel/munit-cats-effect.git#8c07362242fc11a8514d0ee6b54ba9e1ef2f9765"

  extra.exclude: ["docs", "*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
