// https://github.com/typelevel/munit-cats-effect.git#main

vars.proj.munit-cats-effect: ${vars.base} {
  name: "munit-cats-effect"
  uri: "https://github.com/typelevel/munit-cats-effect.git#7de0a8d8bfdb4f6e8540b19737d688f462d3a55e"

  extra.exclude: ["docs", "*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
