// https://github.com/nscala-time/nscala-time.git#master

// dependency of scaladex

vars.proj.nscala-time: ${vars.base} {
  name: "nscala-time"
  uri: "https://github.com/nscala-time/nscala-time.git#6e8d82d346c65460fe6226467d4f9bb4e838aea3"

}
