// https://github.com/nscala-time/nscala-time.git#master

vars.proj.nscala-time: ${vars.base} {
  name: "nscala-time"
  uri: "https://github.com/nscala-time/nscala-time.git#f9bff1d681ad55209a9180dd8b494fadf8971514"

}
