// https://github.com/nscala-time/nscala-time.git#master

vars.proj.nscala-time: ${vars.base} {
  name: "nscala-time"
  uri: "https://github.com/nscala-time/nscala-time.git#966b390fde710af5f837bf2a6038ed3bd55cd1d2"

}
