// https://github.com/sirthias/parboiled.git#master

vars.proj.parboiled: ${vars.base} {
  name: "parboiled"
  uri: "https://github.com/sirthias/parboiled.git#9c98345202c9aca3acb69a2bd5d04fd7aa1e4334"

  extra.projects: ["parboiled-scala"]
  extra.commands: ${vars.default-commands} [
    // override some logic in their build.sbt
    """set every scalaBinaryVersion := "2.13""""
  ]
}
