// https://github.com/sirthias/parboiled.git#master

vars.proj.parboiled: ${vars.base} {
  name: "parboiled"
  uri: "https://github.com/sirthias/parboiled.git#fc0036d63bcc44f4a22edc62e6f248a08852a6cc"

  extra.projects: ["parboiled-scala"]
  extra.commands: ${vars.default-commands} [
    // override some logic in their build.sbt
    """set every scalaBinaryVersion := "2.13""""
  ]
}
