// https://github.com/sirthias/parboiled.git#master

vars.proj.parboiled: ${vars.base} {
  name: "parboiled"
  uri: "https://github.com/sirthias/parboiled.git#4a3ca05b2af9f0b85430a5f47d8db2d58e0559fd"

  extra.projects: ["parboiled-scala"]
  extra.commands: ${vars.default-commands} [
    // override some logic in their build.sbt
    """set every scalaBinaryVersion := "2.13""""
  ]
}
