// https://github.com/sirthias/parboiled2.git#master

vars.proj.parboiled2: ${vars.base} {
  name: "parboiled2"
  uri: "https://github.com/sirthias/parboiled2.git#6d1aaf3ad1988a7794612e26b738062ee310ce31"

  extra.projects: ["parboiledJVM", "examples"]
  extra.commands: ${vars.default-commands} [
    "set every scalafmtOnCompile := false"
  ]
}
