// https://github.com/sirthias/parboiled2.git#master

vars.proj.parboiled2: ${vars.base} {
  name: "parboiled2"
  uri: "https://github.com/sirthias/parboiled2.git#c7da593ae3421d4b5b8e1f3700a49518b4c6a1e6"

  extra.projects: ["parboiledJVM", "examples"]
  extra.commands: ${vars.default-commands} [
    "set every scalafmtOnCompile := false"
  ]
}
