// https://github.com/sirthias/parboiled2.git#master

vars.proj.parboiled2: ${vars.base} {
  name: "parboiled2"
  uri: "https://github.com/sirthias/parboiled2.git#fa44155e3cea79ecd556b22a1a1c014d2dd324ae"

  extra.projects: ["parboiledJVM", "examples"]
  extra.commands: ${vars.default-commands} [
    "set every scalafmtOnCompile := false"
  ]
}
