// https://github.com/ocadotechnology/pass4s.git#main

vars.proj.pass4s: ${vars.base} {
  name: "pass4s"
  uri: "https://github.com/ocadotechnology/pass4s.git#94c61da35e7bbd3854e5a16533e24a9e69657004"

  extra.exclude: [
    "docs"
    // failed because still using -SNAPSHOT versions -- we could maybe re-add eventually
    "*pekko", "pass4s-demo", "root"
  ]
  extra.commands: ${vars.default-commands} [
    // might be removable once they take the 2.13.17 upgrade?
    "appendScalacOptions -Xsource-features:eta-expand-always"
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
