// https://github.com/outr/perfolation.git#master

vars.proj.perfolation:  ${vars.base} {
  name: "perfolation"
  uri: "https://github.com/outr/perfolation.git#bba80994c27a9cb025baa6e1e822549601407b69"

  extra.projects: ["coreJVM"]
}
