// https://github.com/outr/perfolation.git#master

vars.proj.perfolation:  ${vars.base} {
  name: "perfolation"
  uri: "https://github.com/outr/perfolation.git#61ededef27dfb85abb95803359eb8237f32de2f5"

  extra.projects: ["coreJVM"]
}
