// https://github.com/playframework/play-file-watch.git#4a1bfbe43779eb94180b5e5c43ee0b52947ba613  # was main

// frozen (June 2025) at an April 2025 commit before sbt-java-formatter
// was upgraded to a version that doesn't run on Java 8

vars.proj.play-file-watch: ${vars.base} {
  name: "play-file-watch"
  uri: "https://github.com/playframework/play-file-watch.git#4a1bfbe43779eb94180b5e5c43ee0b52947ba613"

  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
