// https://github.com/playframework/play-file-watch.git#main

vars.proj.play-file-watch: ${vars.base} {
  name: "play-file-watch"
  uri: "https://github.com/playframework/play-file-watch.git#7e0d586df148fb31f3ee16c2afca9ef662e12f67"

  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
