// https://github.com/playframework/play-ws.git#main

vars.proj.play-ws: ${vars.base} {
  name: "play-ws"
  uri: "https://github.com/playframework/play-ws.git#152c072dbc712e165b26e0dc908df4ecd3376d49"

  // NullPointerException in CachingSpec
  // (https://github.com/scala/community-builds/issues/564)
  extra.exclude: ["integration-tests", "bench"]
  // tests run forked, so this goes in javaOptions, not extra.options
  extra.commands: ${vars.default-commands} [
    """set `play-ahc-ws-standalone` / Test / javaOptions += "-Dakka.fail-mixed-versions=false""""
  ]
}
