// https://github.com/playframework/play-file-watch.git#main

vars.proj.play-file-watch: ${vars.base} {
  name: "play-file-watch"
  uri: "https://github.com/playframework/play-file-watch.git#056a33455a43a1f73490ea4134ed7ded5e22812d"

  extra.settings: ${vars.base.extra.settings} [
    // dbuild gets confused if only crossScalaVersions is set?!
    """ThisBuild / scalaVersion := "2.13.10""""
  ]
}
