// https://github.com/playframework/playframework.git#f35c9e0f75f88ade2d256532eab2b6c4b25e2892  # was 2.9.x

// perhaps tracking main would work, but I'm inclined to be
// conservative and stick with 2.9.x for a while

// except actually now we're frozen (June 2025) at an April 2025
// commit before sbt-java-formatter was upgraded to a version that
// doesn't run on Java 8, preventing the project from extracting

vars.proj.playframework: ${vars.base} {
  name: "playframework"
  uri: "https://github.com/playframework/playframework.git#f35c9e0f75f88ade2d256532eab2b6c4b25e2892"

  extra.options: [
  ]
  extra.exclude: [
    "Play-Docs", "Sbt-Plugin", "Play-Docs-Sbt-Plugin", "Sbt-Scripted-Tools"  // out of scope
    "Play-Integration-Test"  // TODO/WIP, see https://github.com/scala/community-builds/pull/819
    "Play-Microbenchmark" // out of scope (and besides, requires Play-Integration-Test)
    "Sbt-Routes-Compiler", "Play-Run-Support" // out of scope
  ]
  extra.commands: ${vars.default-commands} [
    "appendScalacOptions -Wconf:cat=scala3-migration:w"
    // tests run forked, so these go in javaOptions, not extra.options
    """set ThisBuild / javaOptions += "-Dakka.fail-mixed-versions=false""""
    """set ThisBuild / javaOptions += "--add-exports=java.base/sun.security.x509=ALL-UNNAMED""""
    """set ThisBuild / javaOptions += "-XX:+IgnoreUnrecognizedVMOptions""""
    // started failing consistently; maybe some site it depends on went down?
    // not investigated or reported
    """set PlayServerProject / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "ServerSSLEngineSpec.scala""""
  ]
}
