// https://github.com/softwaremill/quicklens.git#master

vars.proj.quicklens: ${vars.base} {
  name: "quicklens"
  uri: "https://github.com/softwaremill/quicklens.git#49fc1109b5df6e097926c0758ddbde9e4858889c"

  extra.projects: ["quicklens"]  // this is the 2.13+JVM one
}
