// https://github.com/softwaremill/quicklens.git#master

vars.proj.quicklens: ${vars.base} {
  name: "quicklens"
  uri: "https://github.com/softwaremill/quicklens.git#0b5935c9fde568fcbd505c02c3d6bd4f689d6da6"

  extra.projects: ["quicklens"]  // this is the 2.13+JVM one
}
