// https://github.com/softwaremill/quicklens.git#master

vars.proj.quicklens: ${vars.base} {
  name: "quicklens"
  uri: "https://github.com/softwaremill/quicklens.git#7cf831ee6847c203905d79365c49abceb43c98e3"

  extra.projects: ["quicklens"]  // this is the 2.13+JVM one
}
