// https://github.com/profunktor/redis4cats.git#series/1.x

vars.proj.redis4cats: ${vars.base} {
  name: "redis4cats"
  uri: "https://github.com/profunktor/redis4cats.git#18398e508de5eb163637c8a0f5f323854b41153c"

  // just whatever pfps-shopping-cart needs
  extra.projects: ["redis4cats-core", "redis4cats-effects", "redis4cats-log4cats"]
}
