// https://github.com/profunktor/redis4cats.git#series/1.x

vars.proj.redis4cats: ${vars.base} {
  name: "redis4cats"
  uri: "https://github.com/profunktor/redis4cats.git#54a215878c90f3ef3dd38c06034f6e7cf52ff46e"

  // just whatever pfps-shopping-cart needs
  extra.projects: ["redis4cats-core", "redis4cats-effects", "redis4cats-log4cats"]
}
