// https://github.com/profunktor/redis4cats.git#series/1.x

vars.proj.redis4cats: ${vars.base} {
  name: "redis4cats"
  uri: "https://github.com/profunktor/redis4cats.git#3a3de5b7fa6e2e03902cd2adfd5e56b718839d03"

  // just whatever pfps-shopping-cart needs
  extra.projects: ["redis4cats-core", "redis4cats-effects", "redis4cats-log4cats"]
}
