// https://github.com/fthomas/refined.git#master

vars.proj.refined: ${vars.base} {
  name: "refined"
  uri: "https://github.com/fthomas/refined.git#7525660db6cb546bf2577bce6ecb57f4dfd3e894"

  extra.exclude: ["*JS", "*Native", "benchmark", "docs"]
}
