// https://github.com/fthomas/refined.git#master

vars.proj.refined: ${vars.base} {
  name: "refined"
  uri: "https://github.com/fthomas/refined.git#bb8207d433079d027d8bfdfbcda8ae66af99fbe2"

  extra.exclude: ["*JS", "*Native", "benchmark", "docs"]
}
