// https://github.com/fthomas/refined.git#master

vars.proj.refined: ${vars.base} {
  name: "refined"
  uri: "https://github.com/fthomas/refined.git#dc00b66cacae438dddf33ca9c3a5ca95a3c3432b"

  extra.exclude: ["*JS", "*Native", "benchmark", "docs"]
}
