// https://github.com/takezoe/runtime-scaladoc-reader.git#master

vars.proj.runtime-scaladoc-reader: ${vars.base} {
  name: "runtime-scaladoc-reader"
  uri: "https://github.com/takezoe/runtime-scaladoc-reader.git#5c961d70fbded1d43a202534ab0a35edbe08cfa5"

}
