// https://github.com/sbt/io.git#1.10.x

// (develop branch is now Scala 3 only)

vars.proj.sbt-io: ${vars.base} {
  name: "sbt-io"
  uri: "https://github.com/sbt/io.git#73b32b1dbb0133eb77dc485edaef0caf979caa0f"

  // for JDK 8, as per https://github.com/sbt/sbt/issues/7463 ; might not be necessary
  // anymore by the time we have sbt 1.1.0 final?
  extra.options: ["-Dsbt.io.jdktimestamps=true"]

  extra.commands: ${vars.default-commands} [
    // test allocates large files on `/tmp` which can lead to `IOException: No space left on device` on our infra
    """set io / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "CopySpec.scala""""
  ]
}
