// https://github.com/sbt/sbt-testng.git#main

vars.proj.sbt-testng: ${vars.base} {
  name: "sbt-testng"
  uri: "https://github.com/sbt/sbt-testng.git#61d1446191bd18117f7d8e8e68e549b04f128757"

  extra.sbt-version: ${vars.sbt-0-13-version}
  extra.projects: ["sbt-testng-interface"]  // just the interface, we don't need to build the plugin
  extra.options: [
    ${?SECURITY_MANAGER}
    "-Dbintray.user=dummy", "-Dbintray.pass=dummy"
  ]
  extra.commands: ${vars.default-commands} [
    "set every bintrayReleaseOnPublish := false"
  ]
}
