// https://github.com/typelevel/scalac-options.git#main

vars.proj.scalac-options: ${vars.base} {
  name: "scalac-options"
  uri: "https://github.com/typelevel/scalac-options.git#1c62a60cb0feb282152ccab03aa50b64b171ce95"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
