// https://github.com/scala/scala-collection-compat.git#main

vars.proj.scala-collection-compat: ${vars.base} {
  name: "scala-collection-compat"
  uri: "https://github.com/scala/scala-collection-compat.git#19081e32cf7e1701dd40a6e9043c829bf8e86b36"

  extra.projects: ["compat213"]  // no Scala.js or Scalafix rules plz
  extra.commands: ${vars.default-commands} [
    // in a community build context, we don't want sbt-version-policy
    "set every versionPolicyIntention := Compatibility.None"
  ]
}
