// https://github.com/scalacommunitybuild/scala-parser-combinators.git#community-build-2.13  # was scala, main

// forked (November 2024) to remove `-Wconf:cat=lint-multiarg-infix`;
// we should be able to unfork once they take the 2.13.16 upgrade

vars.proj.scala-parser-combinators: ${vars.base} {
  name: "scala-parser-combinators"
  uri: "https://github.com/scalacommunitybuild/scala-parser-combinators.git#1a1c2446aba782b482d7bf8ee0df24b60ce71ea3"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // work around https://github.com/scala/community-builds/issues/575
    // (in a community build context, we don't need MiMa to run)
    "set every scalaModuleMimaPreviousVersion := None"
    "set parserCombinators.jvm / versionPolicyFindDependencyIssues := Seq()"
    "set parserCombinators.jvm / versionPolicyMimaCheck := {}"
  ]
}
