// https://github.com/xuwei-k/scalafix-rules.git#main

vars.proj.scalafix-rules: ${vars.base} {
  name: "scalafix-rules"
  uri: "https://github.com/xuwei-k/scalafix-rules.git#413f080026632ca9ab109b877e6cec31f6cea15b"

  extra.projects: ["*2_13"]
}
