// https://github.com/scala/scala-library-next.git#main

vars.proj.scala-library-next: ${vars.base} {
  name: "scala-library-next"
  uri: "https://github.com/scala/scala-library-next.git#c9f3fc0a57ae09d3432bed153949674be349dd01"

  extra.exclude: ["*JS"]
}
