// https://github.com/scala/scala-collection-contrib.git#main

vars.proj.scala-collection-contrib: ${vars.base} {
  name: "scala-collection-contrib"
  uri: "https://github.com/scala/scala-collection-contrib.git#de857379b5fa5b011ef995b610389e491e523a1a"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // in a community build context, we don't want sbt-version-policy
    "set every versionPolicyIntention := Compatibility.None"
  ]
}
