// https://github.com/scala/scala-async.git#main

vars.proj.scala-async: ${vars.base} {
  name: "scala-async"
  uri: "https://github.com/scala/scala-async.git#2332b66081e63cbea037f1d3d4541a0716dea07a"

  extra.exclude: ["*JS", "root"]
  extra.commands: ${vars.default-commands} [
    // maybe there's some shorter solution, but...
    "set proj.jvm / versionPolicyFindDependencyIssues := Seq()"
    "set proj.jvm / mimaReportBinaryIssues := {}"
    "set proj.jvm / versionPolicyMimaCheck := {}"
  ]
}
