// https://github.com/scala/scala-xml.git#main

vars.proj.scala-xml: ${vars.base} {
  name: "scala-xml"
  uri: "https://github.com/scala/scala-xml.git#5af150b1a68c61f8e39221535e8fcd291ba644d9"

  extra.projects: ["xml"]
  extra.commands: ${vars.default-commands} [
    // work around https://github.com/scala/community-builds/issues/575
    // (in a community build context, we don't need MiMa to run)
    "set every versionPolicyIntention := Compatibility.None"
  ]
}
