// https://github.com/scala/scala-collection-laws.git#main

vars.proj.scala-collection-laws: ${vars.base} {
  name: "scala-collection-laws"
  uri: "https://github.com/scala/scala-collection-laws.git#864f3d0f6d5e2f56a8a5e63bda4e4d11dd6d9955"

  // as per the repo readme
  extra.options: ["-XX:MaxMetaspaceSize=1G", "-Xmx6G"]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
    // the real testing isn't under `test`
    "laws/run"
  ]
}
