// https://github.com/typelevel/scalac-options.git#main

vars.proj.scalac-options: ${vars.base} {
  name: "scalac-options"
  uri: "https://github.com/typelevel/scalac-options.git#700a252378110b2fc19fedee12f805767b815c16"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
