// https://github.com/scala/scala-parser-combinators.git#main

vars.proj.scala-parser-combinators: ${vars.base} {
  name: "scala-parser-combinators"
  uri: "https://github.com/scala/scala-parser-combinators.git#67da0ed57f9af1fe81b55e5d323fad26be15e7f8"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // work around https://github.com/scala/community-builds/issues/575
    // (in a community build context, we don't need MiMa to run)
    "set every scalaModuleMimaPreviousVersion := None"
    "set parserCombinators.jvm / versionPolicyFindDependencyIssues := Seq()"
    "set parserCombinators.jvm / versionPolicyMimaCheck := {}"
  ]
}
