// https://github.com/scala/scala-async.git#main

vars.proj.scala-async: ${vars.base} {
  name: "scala-async"
  uri: "https://github.com/scala/scala-async.git#4929ce255b0a928e8f0a0630273432f011c6ec0c"

  extra.exclude: ["*JS", "root"]
  extra.commands: ${vars.default-commands} [
    // maybe there's some shorter solution, but...
    "set proj.jvm / versionPolicyFindDependencyIssues := Seq()"
    "set proj.jvm / mimaReportBinaryIssues := {}"
    "set proj.jvm / versionPolicyMimaCheck := {}"
  ]
}
