// https://github.com/scala/scala-collection-compat.git#main

vars.proj.scala-collection-compat: ${vars.base} {
  name: "scala-collection-compat"
  uri: "https://github.com/scala/scala-collection-compat.git#77d28e903a3fb9fa3e40369804a8fb67648db4de"

  extra.projects: ["compat212"]  // no Scala.js or Scalafix rules plz
  extra.commands: ${vars.default-commands} [
    // in a community build context, we don't want sbt-version-policy
    "set every versionPolicyIntention := Compatibility.None"
    // flaky
    """set compat212.jvm/Test/unmanagedSources/excludeFilter := HiddenFileFilter || "LazyListGCTest.scala""""
  ]
}
