// https://github.com/lightbend-labs/scala-logging.git#main

vars.proj.scala-logging: ${vars.base} {
  name: "scala-logging"
  uri: "https://github.com/lightbend-labs/scala-logging.git#cb8a2e29e87a04e2d3c90e1323bc7bbe559baac0"

}
