// https://github.com/scalaprops/scalaprops.git#master

vars.proj.scalaprops: ${vars.base} {
  name: "scalaprops"
  uri: "https://github.com/scalaprops/scalaprops.git#acc80f88b39ca74eda6e41adb51693fd90b0440e"

  extra.projects: ["scalapropsJVM"]  // no Scala.js please
}
