// https://github.com/typelevel/scalac-options.git#main

vars.proj.scalac-options: ${vars.base} {
  name: "scalac-options"
  uri: "https://github.com/typelevel/scalac-options.git#b6f2f84a1f98ca09f51865e974e2001654a0ec65"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
