// https://github.com/lightbend-labs/scala-logging.git#main

vars.proj.scala-logging: ${vars.base} {
  name: "scala-logging"
  uri: "https://github.com/lightbend-labs/scala-logging.git#f7d8ad1dd40c7e18c826109017b67c92126da4d2"

}
