// https://github.com/xuwei-k/scalafix-rules.git#main

vars.proj.scalafix-rules: ${vars.base} {
  name: "scalafix-rules"
  uri: "https://github.com/xuwei-k/scalafix-rules.git#eb894014e9d49308935d12b84a54aac562509c89"

  extra.projects: ["*2_13"]
}
