// https://github.com/scala/scala-collection-laws.git#main

vars.proj.scala-collection-laws: ${vars.base} {
  name: "scala-collection-laws"
  uri: "https://github.com/scala/scala-collection-laws.git#4ec24acf8d10c5773984700a6d75bbcf59600343"

  // as per the repo readme
  extra.options: ["-XX:MaxMetaspaceSize=1G", "-Xmx6G"]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
    // the real testing isn't under `test`
    "laws/run"
  ]
}
