// https://github.com/paulbutcher/ScalaMock.git#master

vars.proj.scalamock: ${vars.base} {
  name: "scalamock"
  uri: "https://github.com/paulbutcher/ScalaMock.git#c73220cf589b54cd6d3485f120bd2f24da4f2a70"

  extra.projects: ["scalamockJVM", "examples"]
}
