// https://github.com/scala/scala-parallel-collections.git#main

vars.proj.scala-parallel-collections: ${vars.base} {
  name: "scala-parallel-collections"
  uri: "https://github.com/scala/scala-parallel-collections.git#910bd6651789be20987a1c2cf86f48d2c9c25d4c"

  extra.exclude: ["*Native"]
  extra.commands: ${vars.default-commands} [
    "set every mimaPreviousArtifacts := Set()"
  ]
}
