// https://github.com/scala/scala-parallel-collections.git#main

vars.proj.scala-parallel-collections: ${vars.base} {
  name: "scala-parallel-collections"
  uri: "https://github.com/scala/scala-parallel-collections.git#4a67a6e7658dc59f66aaef88966d0751a03c40ee"

  extra.exclude: ["*Native"]
  extra.commands: ${vars.default-commands} [
    "set every mimaPreviousArtifacts := Set()"
  ]
}
