// https://github.com/lightbend-labs/scala-logging.git#main

vars.proj.scala-logging: ${vars.base} {
  name: "scala-logging"
  uri: "https://github.com/lightbend-labs/scala-logging.git#abca6244495c6937ec9b5b4d0c720c445c9d232e"

}
