// https://github.com/avsystem/scala-commons.git#master

vars.proj.scala-commons: ${vars.base} {
  name: "scala-commons"
  uri: "https://github.com/avsystem/scala-commons.git#d23708abda9052d890b7375c20c5d34babeb4a8e"

  extra.exclude: [
    "*-js"
    "commons-comprof", "commons-benchmark" // out of scope
  ]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
    // tests here require MongoDB, so only compile them
    "set Commons.mongo / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
  ]
}
