// https://github.com/scalacommunitybuild/scala-commons.git#community-build-2.13  # was avsystem, master

// forked (February 2025) to adjust a macro for 2.13.17, as per
// https://github.com/scala/scala-dev/issues/893

vars.proj.scala-commons: ${vars.base} {
  name: "scala-commons"
  uri: "https://github.com/scalacommunitybuild/scala-commons.git#0fef58188ecf9eada6a07cc318dcac3d67e6959b"

  extra.exclude: [
    "*-js"
    "commons-comprof", "commons-benchmark" // out of scope
  ]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
    // tests here require Redis, so only compile them
    "set Commons.redis / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
    // ditto but MongoDB
    "set Commons.mongo / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
  ]
}
