// https://github.com/scala/scala-xml.git#main

vars.proj.scala-xml: ${vars.base} {
  name: "scala-xml"
  uri: "https://github.com/scala/scala-xml.git#665a2a371a5e89c570c2475815099d0cb68e8ca6"

  extra.projects: ["xml"]
  extra.commands: ${vars.default-commands} [
    // work around https://github.com/scala/community-builds/issues/575
    // (in a community build context, we don't need MiMa to run)
    "set every versionPolicyIntention := Compatibility.None"
  ]
}
