// https://github.com/scala/scala-collection-laws.git#main

vars.proj.scala-collection-laws: ${vars.base} {
  name: "scala-collection-laws"
  uri: "https://github.com/scala/scala-collection-laws.git#b1fa445a23a266354e1f3baf31fd4f0c581dfa3d"

  // as per the repo readme
  extra.options: ["-XX:MaxMetaspaceSize=1G", "-Xmx6G"]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
    // the real testing isn't under `test`
    "laws/run"
  ]
}
