// https://github.com/scala/scala-xml.git#main

vars.proj.scala-xml: ${vars.base} {
  name: "scala-xml"
  uri: "https://github.com/scala/scala-xml.git#848e24e125070a805b4eb6cf036f8f526804337b"

  extra.projects: ["xml"]
  extra.commands: ${vars.default-commands} [
    // work around https://github.com/scala/community-builds/issues/575
    // (in a community build context, we don't need MiMa to run)
    "set every versionPolicyIntention := Compatibility.None"
  ]
}
