// https://github.com/scala-garden/scala-sculpt.git#main

vars.proj.scala-sculpt: ${vars.base} {
  name: "scala-sculpt"
  uri: "https://github.com/scala-garden/scala-sculpt.git#f88d52401f1a7caedf7fc1ddfa2c632a9600d146"

}
