// https://github.com/scallop/scallop.git#develop

// we track develop, since master seems neglected/outdated

vars.proj.scallop: ${vars.base} {
  name: "scallop"
  uri: "https://github.com/scallop/scallop.git#832f839db030b0eab753a208bfcbde90ef244ba7"

  extra.projects: ["scallopJVM"]  // no Scala.js or Scala Native plz
}
