// https://github.com/lightbend-labs/scala-sculpt.git#main

vars.proj.scala-sculpt: ${vars.base} {
  name: "scala-sculpt"
  uri: "https://github.com/lightbend-labs/scala-sculpt.git#3e4b1b009b5cedc74c56e2615adba2121ede7f4f"

}
