// https://github.com/avsystem/scala-commons.git#master

vars.proj.scala-commons: ${vars.base} {
  name: "scala-commons"
  uri: "https://github.com/avsystem/scala-commons.git#150bf6385c88d76496398a8e5bb21e957f90b4df"

  extra.exclude: [
    "*-js"
    "commons-comprof", "commons-benchmark" // out of scope
  ]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
    // tests here require Redis, so only compile them
    "set Commons.redis / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
    // ditto but MongoDB
    "set Commons.mongo / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
  ]
}
