// https://github.com/scala/scala-collection-contrib.git#main

vars.proj.scala-collection-contrib: ${vars.base} {
  name: "scala-collection-contrib"
  uri: "https://github.com/scala/scala-collection-contrib.git#30dcda54db059b8392b41e1b7c27f77cf6a38905"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // in a community build context, we don't want sbt-version-policy
    "set every versionPolicyIntention := Compatibility.None"
  ]
}
