// https://github.com/scalaprops/scalaprops.git#master

vars.proj.scalaprops: ${vars.base} {
  name: "scalaprops"
  uri: "https://github.com/scalaprops/scalaprops.git#ef498f0b85104b57edffe5d1257480bd7204aeaf"

  extra.projects: ["scalapropsJVM"]  // no Scala.js please
}
