// https://github.com/scalaprops/scalaprops.git#master

vars.proj.scalaprops: ${vars.base} {
  name: "scalaprops"
  uri: "https://github.com/scalaprops/scalaprops.git#a37ac7155e5f865aa94847e4116698ecb27263b4"

  extra.projects: ["scalapropsJVM"]  // no Scala.js please
}
