// https://github.com/scalacommunitybuild/scala-collection-compat.git#community-build-2.13  # was scala, main

// forked (April 2025) to in-source new `UsingTest` from Scala 2.13.17;
// we could unfork after 2.13.17 is out and this has been addressed:
// https://github.com/scala/scala-collection-compat/issues/692

vars.proj.scala-collection-compat: ${vars.base} {
  name: "scala-collection-compat"
  uri: "https://github.com/scalacommunitybuild/scala-collection-compat.git#322e24d375bcb6c40814f4d5f9894195baba632b"

  extra.projects: ["compat213"]  // no Scala.js or Scalafix rules plz
  extra.commands: ${vars.default-commands} [
    // in a community build context, we don't want sbt-version-policy
    "set every versionPolicyIntention := Compatibility.None"
  ]
}
