// https://github.com/scala/scala-async.git#main

vars.proj.scala-async: ${vars.base} {
  name: "scala-async"
  uri: "https://github.com/scala/scala-async.git#d6221b2beb786449ae81c810f0255d02dc53d022"

  extra.exclude: ["*JS", "root"]
  extra.commands: ${vars.default-commands} [
    // maybe there's some shorter solution, but...
    "set proj.jvm / versionPolicyFindDependencyIssues := Seq()"
    "set proj.jvm / mimaReportBinaryIssues := {}"
    "set proj.jvm / versionPolicyMimaCheck := {}"
  ]
}
