// https://github.com/ScalaMock/ScalaMock.git#series/7.x

vars.proj.scalamock: ${vars.base} {
  name: "scalamock"
  uri: "https://github.com/ScalaMock/ScalaMock.git#3b57a66c3b44f3b53521e6f77c7c409ab6d9f2f3"

  extra.projects: ["scalamockJVM", "examples"]
}
