// https://github.com/scala/scala-parallel-collections.git#main

vars.proj.scala-parallel-collections: ${vars.base} {
  name: "scala-parallel-collections"
  uri: "https://github.com/scala/scala-parallel-collections.git#97d98906e9faec3d81f9201ba04f056214e6a25c"

  extra.exclude: ["*Native"]
  extra.commands: ${vars.default-commands} [
    "set every mimaPreviousArtifacts := Set()"
  ]
}
