// https://github.com/typelevel/scalacheck-effect.git#main

vars.proj.scalacheck-effect: ${vars.base} {
  name: "scalacheck-effect"
  uri: "https://github.com/typelevel/scalacheck-effect.git#3a8dbaff337b4ab0211b3de4836f199e9c296f4a"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
  ]
}
