// https://github.com/cb372/scala-typed-holes.git#main

vars.proj.scala-typed-holes: ${vars.base} {
  name: "scala-typed-holes"
  uri: "https://github.com/cb372/scala-typed-holes.git#7caebf1b43d5dd993df2f5eb20071bb1c6467588"

  extra.exclude: ["docs", "*-3"]
}
