// https://github.com/lightbend-labs/scala-sculpt.git#main

vars.proj.scala-sculpt: ${vars.base} {
  name: "scala-sculpt"
  uri: "https://github.com/lightbend-labs/scala-sculpt.git#0740fa839e7818f8d9d05f5770186a6e3d715803"

}
