// https://github.com/typelevel/scalacheck-effect.git#main

vars.proj.scalacheck-effect: ${vars.base} {
  name: "scalacheck-effect"
  uri: "https://github.com/typelevel/scalacheck-effect.git#3d589ade681640cd04f0995ed3e4c2aa1bfe04c1"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
    // don't ask for GPG passphrase when running locally
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
