// https://github.com/scala/scala-collection-contrib.git#main

vars.proj.scala-collection-contrib: ${vars.base} {
  name: "scala-collection-contrib"
  uri: "https://github.com/scala/scala-collection-contrib.git#b7027999d92eca7a2ca5597a1bb60588992ce83d"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    // in a community build context, we don't want sbt-version-policy
    "set every versionPolicyIntention := Compatibility.None"
  ]
}
