// https://github.com/xuwei-k/scalafix-rules.git#main

vars.proj.scalafix-rules: ${vars.base} {
  name: "scalafix-rules"
  uri: "https://github.com/xuwei-k/scalafix-rules.git#2793f90624b89498600a3cc5e8204d6a84b28cef"

  extra.projects: ["*2_13"]
}
