// https://github.com/scala/scala-library-next.git#main

vars.proj.scala-library-next: ${vars.base} {
  name: "scala-library-next"
  uri: "https://github.com/scala/scala-library-next.git#3ac0de514c5b42ea569f70a28a8902f4c9e835ab"

  extra.exclude: ["*JS"]
}
