// https://github.com/scala/scala-library-next.git#main

vars.proj.scala-library-next: ${vars.base} {
  name: "scala-library-next"
  uri: "https://github.com/scala/scala-library-next.git#01cbc421e9d0c81ac3f8e39a2c2001627d1073cf"

  extra.exclude: ["*JS"]
}
