// https://github.com/ScalaMock/ScalaMock.git#series/7.x

vars.proj.scalamock: ${vars.base} {
  name: "scalamock"
  uri: "https://github.com/ScalaMock/ScalaMock.git#7ac04aca475783ebdcb082dfd9af68c9db1d4d4b"

  extra.projects: ["scalamockJVM", "examples"]
}
