// https://github.com/scalacommunitybuild/scastie.git#community-build-2.13  # was scalacenter, main

// forked (November 2022) to remove a weird build thing that was
// confusing dbuild; fork updated May 2026 (and one code tweak
// mode for Scalameta 4.17 upgrade)

vars.proj.scastie: ${vars.base} {
  name: "scastie"
  uri: "https://github.com/scalacommunitybuild/scastie.git#7129a23f7b850014463b7d0880c6f9cd0311c522"

  extra.exclude: [
    "*2_10", "*2_11", "*2_12", "*3", "*JS*", "*JS", "client", "sbtScastie"
    // ???, not investigated
    "metalsRunner", "scalaCliRunner"
  ]
  extra.commands: ${vars.default-commands} [
    // integration tests -- out of scope
    "set sbtRunner / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
    "set balancer / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
    // test failure, not investigated
    """set storage / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "SnippetsContainerTest.scala""""
  ]
}
