// https://github.com/ekrich/sconfig.git#main

vars.proj.sconfig: ${vars.base} {
  name: "sconfig"
  uri: "https://github.com/ekrich/sconfig.git#9d398f1b2d98cb0614c3b4c23f8d1e033a1b6ddd"

  extra.exclude: [
    "sconfigNative", "sconfigJS"
  ]
}
