// https://github.com/ekrich/sconfig.git#main

vars.proj.sconfig: ${vars.base} {
  name: "sconfig"
  uri: "https://github.com/ekrich/sconfig.git#cb83c6c4dcbd3e0ab1eaa45bb0adc0cf96020181"

  extra.exclude: [
    "sconfigNative", "sconfigJS"
  ]
}
