// https://github.com/ekrich/sconfig.git#main

vars.proj.sconfig: ${vars.base} {
  name: "sconfig"
  uri: "https://github.com/ekrich/sconfig.git#0da3cc44c10313787fc9d0eebe768949e83b8ff8"

  extra.exclude: [
    "sconfigNative", "sconfigJS"
  ]
}
