// https://github.com/scopt/scopt.git#develop

vars.proj.scopt: ${vars.base} {
  name: "scopt"
  uri: "https://github.com/scopt/scopt.git#8b70fe045c841a53282a218b4bb8849893ac2f49"

  extra.projects: ["scoptJVM"]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
  ]
}
