// https://github.com/scopt/scopt.git#develop

vars.proj.scopt: ${vars.base} {
  name: "scopt"
  uri: "https://github.com/scopt/scopt.git#bd791f4d6db7a63a4617dafc1056a0e92f70e7a3"

  extra.projects: ["scoptJVM"]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
  ]
}
