// https://github.com/scopt/scopt.git#develop

vars.proj.scopt: ${vars.base} {
  name: "scopt"
  uri: "https://github.com/scopt/scopt.git#9512cd03475c4c6421cd6ab5a588cb3e1bb7b7e8"

  extra.projects: ["scoptJVM"]
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xsource:3"
    "appendScalacOptions -Xsource:3-cross"
  ]
}
