// https://github.com/scoverage/scalac-scoverage-plugin.git#main

vars.proj.scoverage: ${vars.base} {
  name: "scoverage"
  uri: "https://github.com/scoverage/scalac-scoverage-plugin.git#36c84062f2f3f5394c308d40447ccf5e87a4e999"

  extra.exclude: ["*JS*", "*Native"]
  extra.commands: ${vars.default-commands} [
    // so we don't have to arrange for dbuild-built semanticdb to be brought in
    "set every semanticdbEnabled := false"
    // plugin project has `dependsOn(runtimeJVM % Test, runtimeJS % Test)`
    "removeDependency org.scala-js scalajs-compiler"
    // this additionally became needed after upgrading from Scala.js 1.14.0 to 1.15.0
    "removeDependency org.scala-js scalajs-scalalib"
    // these tests can't find nightly Scala; maybe fixable, not sure
    "set plugin / Test / executeTests := Tests.Output(TestResult.Passed, Map(), Iterable())"
  ]
}
