// https://github.com/xuwei-k/shapeless-java-records.git#main

vars.proj.shapeless-java-records: ${vars.base} {
  name: "shapeless-java-records"
  uri: "https://github.com/xuwei-k/shapeless-java-records.git#807c986b74586c26e519d292a8d9640ed5e99c77"

  extra.options: ["--enable-preview", "-XX:+IgnoreUnrecognizedVMOptions"]
}
