// https://github.com/milessabin/shapeless.git#main

vars.proj.shapeless: ${vars.base} {
  name: "shapeless"
  uri: "https://github.com/milessabin/shapeless.git#de985e8952111d64317bcf589719f4a25ffdf9d2"

  extra.projects: ["coreJVM"]
}
