// https://github.com/milessabin/shapeless.git#main

vars.proj.shapeless: ${vars.base} {
  name: "shapeless"
  uri: "https://github.com/milessabin/shapeless.git#09632d7215472fc42e7733cb6148448baaeff2a9"

  extra.projects: ["coreJVM"]
}
