// https://github.com/xuwei-k/shapeless-java-records.git#main

vars.proj.shapeless-java-records: ${vars.base} {
  name: "shapeless-java-records"
  uri: "https://github.com/xuwei-k/shapeless-java-records.git#0d2b4983c99990852b3d39cc8a4a965dc1f080ca"

  extra.options: ["--enable-preview", "-XX:+IgnoreUnrecognizedVMOptions"]
}
