// https://github.com/xuwei-k/shapeless-java-records.git#main

vars.proj.shapeless-java-records: ${vars.base} {
  name: "shapeless-java-records"
  uri: "https://github.com/xuwei-k/shapeless-java-records.git#75f885e2e390c0cce31fb8ff4b11544ef8035295"

  extra.options: ["--enable-preview", "-XX:+IgnoreUnrecognizedVMOptions"]
}
