// https://github.com/milessabin/shapeless.git#main

vars.proj.shapeless: ${vars.base} {
  name: "shapeless"
  uri: "https://github.com/milessabin/shapeless.git#402c7234965b683425327d777485bd5b291585e0"

  extra.projects: ["coreJVM"]
}
