// https://github.com/scalacommunitybuild/slick.git#community-build-2.13  # was slick, main

// forked (February 2025) for 2.13.16 compatibility -- they haven't
// taken the 2.13.16 upgrade yet

vars.proj.slick: ${vars.base} {
  name: "slick"
  uri: "https://github.com/scalacommunitybuild/slick.git#9a93fdb91ac599634a47211d121f4b1b0cd6863f"

  extra.exclude: [
    // unless we exclude, it looks for an Ornate dependency here
    "root"
  ]
  extra.commands: ${vars.default-commands} [
    // fails on JDK 20
    """set testkit / Test / unmanagedSources / excludeFilter := HiddenFileFilter || "MBeansTest.scala""""
  ]
}
