// https://github.com/scalacommunitybuild/sourcecode.git#community-build-2.13  # was lihaoyi, main

// forked (December 2020) to add sbt build (instead of mill)
// fork updated October 2025

vars.proj.sourcecode: ${vars.base} {
  name: "sourcecode"
  uri: "https://github.com/scalacommunitybuild/sourcecode.git#c078828259b0e853e4fbd3ec97f8bb9b2210f8f4"

}
