// https://github.com/typelevel/sourcepos.git#main

vars.proj.sourcepos: ${vars.base} {
  name: "sourcepos"
  uri: "https://github.com/typelevel/sourcepos.git#476dbed940b5b6e32bc6d7b26bfdb5bfcca913a6"

  extra.exclude: ["*JS", "*Native"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    """set every gpgOptions := Seq("--yes", "--passphrase", "", "--pinentry-mode", "loopback")"""
  ]
}
