// https://github.com/scalacommunitybuild/specs2.git#community-build-2.13  # was etorreborre, specs2-4.x-maintenance

// forked (November 2024) to remove `-Wconf:cat=lint-multiarg-infix`;
// we should be able to unfork once they take the 2.13.16 upgrade

vars.proj.specs2: ${vars.base} {
  name: "specs2"
  uri: "https://github.com/scalacommunitybuild/specs2.git#dfdce2c81301a93585ed92d60051ff36d72f2142"

  extra.exclude: [
    "*JS", "*Native", "scalaz*", "guide"
    // markdown stuff uses parboiled2 which doesn't work on JDK 17
    "markdown*"
  ]
  // we should be able to remove this once this issue is resolved:
  // https://github.com/scala/scala-dev/issues/893
  extra.commands: ${vars.default-commands} [
    "removeScalacOptions -Xlint"
    "appendScalacOptions -Xlint:-implicit-recursion"
  ]
}
