// https://github.com/typelevel/spire.git#main

vars.proj.spire: ${vars.base} {
  name: "spire"
  uri: "https://github.com/typelevel/spire.git#0fe5a6a9714181a20fc9cef4c8b2af088ff2b4c9"

  // hopefully avoid intermittent OutOfMemoryErrors during compilation
  extra.options: ["-Xmx3G"]
  extra.projects: ["*JVM"]
  extra.exclude: ["benchmark"]
  extra.commands: ${vars.default-commands} [
    // otherwise sbt-gpg errors on `publish`
    "set every gpgWarnOnFailure := true"
    // jmh stuff is out of scope
    "removeDependency org.openjdk.jmh jmh-core"
    "removeDependency org.openjdk.jmh jmh-generator-bytecode"
    "removeDependency org.openjdk.jmh jmh-generator-reflection"
  ]
}
