// https://github.com/typelevel/squants.git#master

vars.proj.squants: ${vars.base} {
  name: "squants"
  uri: "https://github.com/typelevel/squants.git#29aa57f4a1958daf9a5a397cca8982b1654e164c"

  extra.projects: ["squantsJVM"]
}
