// https://github.com/softwaremill/sttp-shared.git#master

vars.proj.sttp-shared: ${vars.base} {
  name: "sttp-shared"
  uri: "https://github.com/softwaremill/sttp-shared.git#0c2351a783b40b110be85d0ec7e4dfe3559359b9"

  extra.projects: [
    // needed by sttp's core
    "core", "ws"
    // bonus integrations used downstream in sttp's integrations
    "fs2", "akka", "monix"
  ]
}
