// https://github.com/softwaremill/sttp.git#master

vars.proj.sttp: ${vars.base} {
  name: "sttp"
  uri: "https://github.com/softwaremill/sttp.git#6b817f72a1e7343d816d669b3da6f58a4f284ce3"

  extra.exclude: [
    "*JS", "*Native", "*2_11", "*2_12", "*3", "examples*",
    "*scalaz*", "*Scalaz*", "*zio*", "*Zio*"
    // test failures, not investigated
    "prometheusBackend"
    // compilation failures, not investigated
    "httpClient*Backend*"
  ]
  extra.options: [
    // I saw an OutOfMemoryError, hopefully this will help
    "-Xmx4G"
    // this is for the tests that run unforked...
    "-Dakka.fail-mixed-versions=false"
  ]
  extra.commands: ${vars.default-commands} [
    // ...and this is for the tests that run forked
    """set ThisBuild / javaOptions += "-Dakka.fail-mixed-versions=false""""
    // many intermittent failures otherwise
    "set every closeClassLoaders := false"
  ]
}
