// https://github.com/softwaremill/sttp-shared.git#master

vars.proj.sttp-shared: ${vars.base} {
  name: "sttp-shared"
  uri: "https://github.com/softwaremill/sttp-shared.git#1928bfcce3550ec36a8f369db9e183a937343978"

  extra.projects: [
    // needed by sttp's core
    "core", "ws"
    // bonus integrations used downstream in sttp's integrations
    "fs2", "akka", "monix"
  ]
}
