// https://github.com/softwaremill/sttp-model.git#master

vars.proj.sttp-model: ${vars.base} {
  name: "sttp-model"
  uri: "https://github.com/softwaremill/sttp-model.git#ecaed19428555779ae6eeaab4579047c64989081"

  extra.projects: ["core"]
}
