// https://github.com/softwaremill/sttp-model.git#master

vars.proj.sttp-model: ${vars.base} {
  name: "sttp-model"
  uri: "https://github.com/softwaremill/sttp-model.git#263808882e901976a5732b11f2e9b756307f3e55"

  extra.projects: ["core"]
}
