// https://github.com/softwaremill/sttp-shared.git#master

vars.proj.sttp-shared: ${vars.base} {
  name: "sttp-shared"
  uri: "https://github.com/softwaremill/sttp-shared.git#64a0c84e590715ee6d6db2319f0dc4906b911eed"

  extra.projects: [
    // needed by sttp's core
    "core", "ws"
    // bonus integrations used downstream in sttp's integrations
    "fs2", "akka", "monix"
  ]
}
