// https://github.com/softwaremill/sttp-model.git#master

vars.proj.sttp-model: ${vars.base} {
  name: "sttp-model"
  uri: "https://github.com/softwaremill/sttp-model.git#72fb9aba212170bcb92051cf8bc925797a9c3e9c"

  extra.projects: ["core"]
}
