// https://github.com/eed3si9n/treehugger.git#36fd4952f92995e5fa81d4f229c677e2107d7ba9  # was main

// frozen (May 2026) at known green commit before sbt 2 upgrade

vars.proj.treehugger: ${vars.base} {
  name: "treehugger"
  uri: "https://github.com/eed3si9n/treehugger.git#36fd4952f92995e5fa81d4f229c677e2107d7ba9"

  extra.exclude: ["root"]
}
