// https://github.com/eed3si9n/treehugger.git#main

vars.proj.treehugger: ${vars.base} {
  name: "treehugger"
  uri: "https://github.com/eed3si9n/treehugger.git#b361b8ab3021fe5a91f65396e2471d3b4bb20ef7"

  extra.exclude: ["root"]
}
