// https://github.com/typelevel/twiddles.git#main

vars.proj.twiddles: ${vars.base} {
  name: "twiddles"
  uri: "https://github.com/typelevel/twiddles.git#d7a71bf17153a33373ed48582e48571b75c80308"

  extra.options: ["-Xss16m"]
  extra.exclude: ["*JS", "*Native", "docs"]
  extra.commands: ${vars.default-commands} [
    "set every gpgWarnOnFailure := true"
    // prevent sbt-gpg from asking for passphrase when running locally
    """set every gpgKey := Some("")"""
  ]
}
