// https://github.com/tpolecat/typename.git#main

vars.proj.typename: ${vars.base} {
  name: "typename"
  uri: "https://github.com/tpolecat/typename.git#1c5bf84cdb699f24ff1634104b3b0eb2afd7c385"

  extra.exclude: ["*JS", "*Native"]
}
