// https://github.com/unfiltered/unfiltered.git#main

vars.proj.unfiltered: ${vars.base} {
  name: "unfiltered"
  uri: "https://github.com/unfiltered/unfiltered.git#88a831b10988498064c2adc9e50d92acf08733e0"

}
