// https://github.com/unfiltered/unfiltered.git#main

vars.proj.unfiltered: ${vars.base} {
  name: "unfiltered"
  uri: "https://github.com/unfiltered/unfiltered.git#cc33308f306f729b6de43e644e556f8a25e1037f"

}
