// https://github.com/unfiltered/unfiltered.git#main

vars.proj.unfiltered: ${vars.base} {
  name: "unfiltered"
  uri: "https://github.com/unfiltered/unfiltered.git#30f2fefb1f2c7967378dd68973081740e88a06fb"

}
