// https://github.com/xuwei-k/unused-code.git#main

vars.proj.unused-code: ${vars.base} {
  name: "unused-code"
  uri: "https://github.com/xuwei-k/unused-code.git#49893af682ba489e3aeeb25bb8b7420465b2c50e"

  extra.projects: ["*2_13"]
}
