// https://github.com/xuwei-k/unused-code.git#main

vars.proj.unused-code: ${vars.base} {
  name: "unused-code"
  uri: "https://github.com/xuwei-k/unused-code.git#cfd4e908c0573424dab6e4e94e056f7f0496f9ad"

  extra.projects: ["*2_13"]
}
