// https://github.com/xuwei-k/unused-code.git#main

vars.proj.unused-code: ${vars.base} {
  name: "unused-code"
  uri: "https://github.com/xuwei-k/unused-code.git#8c585e0295248210c6dd2413c9549d960711e895"

  extra.projects: ["*2_13"]
}
