// https://github.com/scalacommunitybuild/utest.git#community-build-2.13  # was com-lihaoyi, master

// forked to add sbt build (instead of mill)
// (fork updated August 2025)

vars.proj.utest: ${vars.base} {
  name: "utest"
  uri: "https://github.com/scalacommunitybuild/utest.git#c2bba81be232d284398fcaa19c9cfeb6d7ba230d"

  extra.commands: ${vars.default-commands} [
    // latest portable-scala-reflect makes scala-reflect dependency "provided".
    // this can probably be removed eventually, once this repo depends on
    // a newer release of portable-scala-reflect
    """set libraryDependencies += "org.scala-lang" %% "scala-reflect" % "0""""
  ]
}
