// https://github.com/scalacommunitybuild/utest.git#community-build-2.13  # was com-lihaoyi, master

// forked to add sbt build (instead of mill)
// (fork updated November 2025)

vars.proj.utest: ${vars.base} {
  name: "utest"
  uri: "https://github.com/scalacommunitybuild/utest.git#01a18d39df2540172158c055eb01b68915f7f9e4"

}
