// https://github.com/eed3si9n/verify.git#main

vars.proj.verify: ${vars.base} {
  name: "verify"
  uri: "https://github.com/eed3si9n/verify.git#1db025d679ee08cc4ea69a329748257a6f0b6965"

  extra.projects: ["verifyJVM"]
}
