// https://github.com/eed3si9n/verify.git#main

vars.proj.verify: ${vars.base} {
  name: "verify"
  uri: "https://github.com/eed3si9n/verify.git#fddab89b61c0941d6a660ef0f576212bd784baa2"

  extra.projects: ["verifyJVM"]
}
