// https://github.com/eed3si9n/verify.git#main

vars.proj.verify: ${vars.base} {
  name: "verify"
  uri: "https://github.com/eed3si9n/verify.git#30ef4ea524b68cf77b494801e11ef37cef6a9b7d"

  extra.projects: ["verifyJVM"]
}
