// https://github.com/typelevel/weaver-test.git#main

// extraction fails locally with:
//   [weaver-test:error] Error downloading object: docs/assets/oops.png (2712f5a): Smudge error: Error downloading docs/assets/oops.png (2712f5af71bd4afdacc3f0b6ce67d5b63feff71b35a96cf438a335e42e6b49a9): error transferring "2712f5af71bd4afdacc3f0b6ce67d5b63feff71b35a96cf438a335e42e6b49a9": [0] remote missing object 2712f5af71bd4afdacc3f0b6ce67d5b63feff71b35a96cf438a335e42e6b49a9
// and I don't know why.
// but it succeeds on Jenkins so we don't care that much

vars.proj.weaver-test: ${vars.base} {
  name: "weaver-test"
  uri: "https://github.com/typelevel/weaver-test.git#1ed9d492cc19311383e1a59bc68661933d645d06"

  extra.exclude: [
    "docs", "*JS", "*Native", "zio*", "*2_12"
    // intended to exclude Scala 3 but also ends up including some CE3 things. oh well
    "*3"
  ]
  extra.commands: ${vars.default-commands} [
    // so we don't have to arrange for dbuild-built semanticdb to be brought in
    "set every semanticdbEnabled := false"
  ]
}
